/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.admin;

import api.Role.AirCaptain;
import api.Role.AirlineComManager;
import api.Role.AirportControl;
import api.Role.Customer;
import api.Role.CustomerService;
import api.Role.RailwayComManager;
import api.Role.StationControl;
import api.Role.TrainCaptain;
import api.Role.VIPCustomer;
import api.Role.VIPCustomerService;
import api.employee.Employee;
import api.organization.Organization;
import api.request.requestDirectory;
import api.userAccount.UserAccount;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author 10857
 */
public class SysAccount extends javax.swing.JFrame {

    /**
     * Creates new form SysAccountAdd
     */
    Organization organization;
    UserAccount user;
    Employee employee;
    public SysAccount(Organization o, int mode, String userName, String Enter, String Or,String Role, String Status) {//Organization o, int mode, String userName, String Enter, String Or, String Role, String Status
        initComponents();
        this.organization = o;
        lblEnterValue.setText(Enter);
        lblOrValue.setText(Or);
        lblRoleValue.setText(Role);
        lblStatusValue.setText(Status);
        
        if(Role.equals("Customer")||Role.equals("VIPCustomer")){
            for(UserAccount u : this.organization.getUserAccountDirectory().getUserAccountList()){
                if(u.getUsername().equals(userName)){
                    txtAccountName.setText(u.getUsername());
                    txtPassword.setText(u.getPassword());
                    txtRealName.setText(u.getRealName());
                }
            }
            lblSalary.setVisible(false);
            txtSalary.setVisible(false);
        }
        else{
            lblSalary.setVisible(true);
            txtSalary.setVisible(true);
            for(Employee e : this.organization.getEmployeeDirectory().getEmployeeList()){
                if(e.getEmployeeAccount().equals(userName)){
                    txtAccountName.setText(e.getEmployeeAccount());
                    txtPassword.setText(e.getEmployeePassword());
                    txtRealName.setText(e.getName());
                    txtSalary.setText(String.valueOf(e.getSalary()));
                }
            }
        }
        txtAccountName.setEnabled(false);
        if(mode == 0){
            BtnUpdate.setVisible(false);
            BtnAdd.setVisible(true);
            txtAccountName.setEnabled(true);
            lblStatusValue.setText("Activated");
            txtAccountName.setText("");
            txtPassword.setText("");
            txtRealName.setText("");
            txtSalary.setText("");  
        }
        else{
            BtnUpdate.setVisible(true);
            BtnAdd.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnter = new javax.swing.JLabel();
        lblOr = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblAccountName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblRealName = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        lblEnterValue = new javax.swing.JLabel();
        lblOrValue = new javax.swing.JLabel();
        lblRoleValue = new javax.swing.JLabel();
        txtAccountName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtRealName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        lblStatusValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEnter.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblEnter.setText("Enterprise: ");
        getContentPane().add(lblEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 103, -1, 20));

        lblOr.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblOr.setText("Organization: ");
        getContentPane().add(lblOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 142, -1, 20));

        lblRole.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblRole.setText("Role: ");
        getContentPane().add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 181, -1, 20));

        lblAccountName.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblAccountName.setText("AccountName: ");
        getContentPane().add(lblAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 257, -1, 20));

        lblPassword.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblPassword.setText("Password: ");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 302, -1, 20));

        lblRealName.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblRealName.setText("RealName: ");
        getContentPane().add(lblRealName, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 347, -1, 20));

        lblSalary.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblSalary.setText("Salary: ");
        getContentPane().add(lblSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 392, -1, 20));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/admin/Backbutton_3.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, 60));

        BtnAdd.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 431, 87, 30));

        BtnUpdate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 475, -1, 30));

        lblEnterValue.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblEnterValue.setText("jLabel2");
        getContentPane().add(lblEnterValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 103, -1, 20));

        lblOrValue.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblOrValue.setText("jLabel3");
        getContentPane().add(lblOrValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 142, -1, 20));

        lblRoleValue.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblRoleValue.setText("jLabel4");
        getContentPane().add(lblRoleValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 181, -1, 20));

        txtAccountName.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        getContentPane().add(txtAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 254, 96, 30));

        txtPassword.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 299, 96, 30));

        txtRealName.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtRealName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRealNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtRealName, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 344, 96, 30));

        txtSalary.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 389, 96, 30));

        lblStatus.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblStatus.setText("Status: ");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 220, -1, 20));

        lblStatusValue.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblStatusValue.setText("jLabel3");
        getContentPane().add(lblStatusValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 220, -1, 20));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account Add");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 240, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/admin/admin_200.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 210, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRealNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRealNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRealNameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        Boolean flag = true;
        if(txtAccountName.getText().matches("^[0-9A-Za-z]+$")){
            txtAccountName.setForeground(Color.black);
        }
        else{
            flag = false;
            txtAccountName.setForeground(Color.red);
        }
        if(txtRealName.getText().matches("^[A-Za-z ]+$")){
            txtRealName.setForeground(Color.black);
        }
        else{
            flag = false;
            txtRealName.setForeground(Color.red);
        }
        if(txtPassword.getText().matches("^[ ]+$")||txtPassword.getText().equals("")){
            flag = false;
            txtPassword.setForeground(Color.red);
        }
        else{
            txtPassword.setForeground(Color.black);
        }
        if(lblRoleValue.getText().endsWith("Customer")){
            if(!this.organization.getUserAccountDirectory().accountNameCheck(txtAccountName.getText()) || txtAccountName.getText().equals("sysadmin")){
                txtAccountName.setForeground(Color.red);
                flag = false;
            }
        }
        else{
            if(txtSalary.getText().matches("^[0-9]+$")){
                txtSalary.setForeground(Color.black);
            }
            else{
                txtSalary.setForeground(Color.red);
                flag = false;
            }
            if(!this.organization.getEmployeeDirectory().accountNameCheck(txtAccountName.getText()) || txtAccountName.getText().equals("sysadmin")){
                txtAccountName.setForeground(Color.red);
                flag = false;
            }
        }
        
        if(flag){
            if(lblRoleValue.getText().equals("Customer")){
                this.organization.getUserAccountDirectory().addUser(new UserAccount(txtAccountName.getText(), txtPassword.getText(), this.organization.getUserAccountDirectory().getUserAccountList().size() + 1, txtRealName.getText(), new Customer(), new requestDirectory()));
            }
            else if(lblRoleValue.getText().equals("VIPCustomer")){
                this.organization.getUserAccountDirectory().addUser(new UserAccount(txtAccountName.getText(), txtPassword.getText(), this.organization.getUserAccountDirectory().getUserAccountList().size() + 1, txtRealName.getText(), new VIPCustomer(), new requestDirectory()));
            }
            else if(lblRoleValue.getText().equals("AirCaptain")){
                this.organization.getEmployeeDirectory().getEmployeeList().add(new Employee(txtRealName.getText(), this.organization.getEmployeeDirectory().getEmployeeList().size() + 1, txtAccountName.getText(), txtPassword.getText(), Integer.valueOf(txtSalary.getText()), new AirCaptain()));
            }
            else if(lblRoleValue.getText().equals("AirlineComManager")){
                this.organization.getEmployeeDirectory().getEmployeeList().add(new Employee(txtRealName.getText(), this.organization.getEmployeeDirectory().getEmployeeList().size() + 1, txtAccountName.getText(), txtPassword.getText(), Integer.valueOf(txtSalary.getText()), new AirlineComManager()));
            }
            else if(lblRoleValue.getText().equals("AirportControl")){
                this.organization.getEmployeeDirectory().getEmployeeList().add(new Employee(txtRealName.getText(), this.organization.getEmployeeDirectory().getEmployeeList().size() + 1, txtAccountName.getText(), txtPassword.getText(), Integer.valueOf(txtSalary.getText()), new AirportControl()));
            }
            else if(lblRoleValue.getText().equals("CustomerService")){
                this.organization.getEmployeeDirectory().getEmployeeList().add(new Employee(txtRealName.getText(), this.organization.getEmployeeDirectory().getEmployeeList().size() + 1, txtAccountName.getText(), txtPassword.getText(), Integer.valueOf(txtSalary.getText()), new CustomerService()));
            }
            else if(lblRoleValue.getText().equals("VIPCustomerService")){
                this.organization.getEmployeeDirectory().getEmployeeList().add(new Employee(txtRealName.getText(), this.organization.getEmployeeDirectory().getEmployeeList().size() + 1, txtAccountName.getText(), txtPassword.getText(), Integer.valueOf(txtSalary.getText()), new VIPCustomerService()));
            }
            else if(lblRoleValue.getText().equals("RailwayCompanyManager")){
                this.organization.getEmployeeDirectory().getEmployeeList().add(new Employee(txtRealName.getText(), this.organization.getEmployeeDirectory().getEmployeeList().size() + 1, txtAccountName.getText(), txtPassword.getText(), Integer.valueOf(txtSalary.getText()), new RailwayComManager()));
            }
            else if(lblRoleValue.getText().equals("StationControl")){
                this.organization.getEmployeeDirectory().getEmployeeList().add(new Employee(txtRealName.getText(), this.organization.getEmployeeDirectory().getEmployeeList().size() + 1, txtAccountName.getText(), txtPassword.getText(), Integer.valueOf(txtSalary.getText()), new StationControl()));
            }
            else if(lblRoleValue.getText().equals("TrainCaptain")){
                this.organization.getEmployeeDirectory().getEmployeeList().add(new Employee(txtRealName.getText(), this.organization.getEmployeeDirectory().getEmployeeList().size() + 1, txtAccountName.getText(), txtPassword.getText(), Integer.valueOf(txtSalary.getText()), new TrainCaptain()));
            }
            
            JOptionPane.showMessageDialog(this, "add success");
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "userName existed or input invalid");
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        Boolean flag = true;
        if(txtRealName.getText().matches("^[A-Za-z ]+$")){
            txtRealName.setForeground(Color.black);
        }
        else{
            flag = false;
            txtRealName.setForeground(Color.red);
        }
        if(txtPassword.getText().matches("^[ ]+$")||txtPassword.getText().equals("")){
            flag = false;
            txtPassword.setForeground(Color.red);
        }
        else{
            txtPassword.setForeground(Color.black);
        }
        if(!lblRoleValue.getText().endsWith("Customer")){
            if(txtSalary.getText().matches("^[0-9]+$")){
                txtSalary.setForeground(Color.black);
            }
            else{
                txtSalary.setForeground(Color.red);
                flag = false;
            }
        }
        
        if(flag){
            if(lblRoleValue.getText().endsWith("Customer")){
                for(UserAccount u : this.organization.getUserAccountDirectory().getUserAccountList()){
                    if(u.getUsername().equals(txtAccountName.getText())){
                        u.setPassword(txtPassword.getText());
                        u.setRealName(txtRealName.getText());
                    }
                }
            }
            else{
                for(Employee e : this.organization.getEmployeeDirectory().getEmployeeList()){
                    if(e.getEmployeeAccount().equals(txtAccountName.getText())){
                        e.setName(txtRealName.getText());
                        e.setEmployeePassword(txtPassword.getText());
                        e.setSalary(Integer.valueOf(txtSalary.getText()));
                    }
                }
            }
            
           JOptionPane.showMessageDialog(this, "update success");
           this.setVisible(false);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAccountName;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblEnterValue;
    private javax.swing.JLabel lblOr;
    private javax.swing.JLabel lblOrValue;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRealName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoleValue;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusValue;
    private javax.swing.JTextField txtAccountName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRealName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
