/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AirlineCompany;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.organization.AirlineCompany;
import api.organization.Organization;
import api.request.Flight;
import api.request.request;

/**
 *
 * @author Lynn Wei
 */
public class ShowFlightJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private List<request> flightList = new ArrayList<>();
    public ShowFlightJPanel(JPanel userProcessContainer, Employee employee, TravelSystem system, Organization origanization) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        initComponents();
        initFlight();
        populateRequestTable();
    }
    
    private void initFlight() {
        AirlineCompany airLineCompany = (AirlineCompany)origanization;
        List<request> requests = airLineCompany.getRequestDirectory().getRequestList();
        for (request request : requests) {
            // Unsolved Canceled
            if (request instanceof Flight
                && !request.getStatus().equals("Unsolved")
                && !request.getStatus().equals("Canceled")) {
                flightList.add(request);
            }
        }
    }
    private void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int size = model.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
        for (request request : flightList) {
            Flight flight = (Flight)request;
            Object[] row = new Object[7];
            row[0] = flight.getId();
            row[1] = flight.getStartAirport();
            row[2] = flight.getEndAirport();
            row[3] = null == flight.getCaptain() ? "" : flight.getCaptain().getName();
            SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
            row[4] = sdf.format(flight.getStartDate() == null ? new Date() : flight.getStartDate());
            row[5] = flight.getType();
            row[6] = flight.getStatus();
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton4.setText(">>Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle1.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblTitle1.setText("Flight Information");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jScrollPane1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N

        jTable1.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight Number", "Departure Airport", "Landing Airport", "Captain", "Departure Date", "Flight Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 137, 873, 306));

        btnAdd.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnAdd.setText("Add Flight");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 160, -1));

        btnView.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnView.setText("View Flight");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 160, 50));

        btnDelete.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnDelete.setText("Delete Flight");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 160, 50));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/airplane1_1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/airplane2_2.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 860, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        UpdateFlightJPanel rwajp = new UpdateFlightJPanel(userProcessContainer, employee, system, 
            origanization, (Flight)flightList.get(i));
        userProcessContainer.add("UpdateFlightJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int fightId = Integer.parseInt(model.getValueAt(i, 0).toString());
        AirlineCompany airLineCompany = (AirlineCompany)origanization;
        List<request> requests = airLineCompany.getRequestDirectory().getRequestList();
        for (request request : requests) {
            if (request instanceof Flight) {
                Flight flight = (Flight)request;
                if (flight.getId() == fightId) {
                    requests.remove(request);
                    break;
                }
            }
        }
        flightList.remove(i);
        model.removeRow(i);
        DB4OUtil.getInstance().storeSystem(system);
        JOptionPane.showMessageDialog(null, "Information Deleted Succesfully!");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddFlightJPanel rwajp = new AddFlightJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("AddFlightJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AirlineCompanyPanel rwajp = new AirlineCompanyPanel(userProcessContainer, null, employee, system, origanization);
        userProcessContainer.add("AirlineCompanyPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
