/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AirlineCompany;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import api.BoxHelper;
import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.enterprise.Enterprise;
import api.organization.AirlineCompany;
import api.organization.Airport;
import api.organization.Organization;
import api.property.Airplane;
import api.request.Flight;
import api.request.request;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Lynn Wei
 */
public class UpdateFlightJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private Flight flight;
    private BoxHelper<Airplane>[] airList = new BoxHelper[0];
    private BoxHelper<Airport>[] airportList = new BoxHelper[0];
    private BoxHelper<Employee>[] airCaptainList = new BoxHelper[0];
    private SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
    
    public UpdateFlightJPanel(JPanel userProcessContainer, Employee employee, 
        TravelSystem system, Organization origanization, Flight flight) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        this.flight = flight;
        AirlineCompany airLineCompany = (AirlineCompany)origanization;
        List<Airplane> airplaneList = airLineCompany.getAirplaneList();
        airList = new BoxHelper[airplaneList.size()];
        for (int i = 0; i < airList.length; i++) {
            airList[i] = new BoxHelper<>(airplaneList.get(i).getId(), airplaneList.get(i));
        }
        
        // Airport
        getAirPortList();
        getEmployeeList();
        initComponents();
    }
    
    private void getAirPortList() {
        ArrayList<Enterprise> enterpriseList = system.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise enterprise : enterpriseList) {
            if (enterprise.getName().equals("Airport")) {
                List<Organization> orgList = enterprise.getOrganizationDirectory().getOrganizationList();
                airportList = new BoxHelper[orgList.size()];
                for (int i = 0; i < orgList.size(); i++) {
                    Airport airport = (Airport)orgList.get(i);
                    airportList[i] = new BoxHelper<>(airport.getId(), airport);
                }
            }
        }
    }
    
    private void getEmployeeList() {
        AirlineCompany airLineCompany = (AirlineCompany)origanization;
        List<Employee> employeeList = new ArrayList<>();
        for (Employee employee : airLineCompany.getEmployeeDirectory().getEmployeeList()) {
            if (employee.getRole().getRole().equals("AirCaptain")) {
                employeeList.add(employee);
            }
        }
        airCaptainList = new BoxHelper[employeeList.size()];
        for (int i = 0; i < employeeList.size(); i++) {
            airCaptainList[i] = new BoxHelper<>(employeeList.get(i).getName(), employeeList.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        lblTitle8 = new javax.swing.JLabel();
        txtEcoNum = new javax.swing.JTextField();
        txtEcoPrice = new javax.swing.JTextField();
        txtBusiNum = new javax.swing.JTextField();
        txtBusiPrice = new javax.swing.JTextField();
        lblTitle18 = new javax.swing.JLabel();
        lblTitle19 = new javax.swing.JLabel();
        txtFirstNum = new javax.swing.JTextField();
        txtFirstPrice = new javax.swing.JTextField();
        lblTitle20 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle9 = new javax.swing.JLabel();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle16 = new javax.swing.JLabel();
        cmbPlaneId = new javax.swing.JComboBox<>();
        cmbDeAirport = new javax.swing.JComboBox<>();
        cmbLandAirport = new javax.swing.JComboBox<>();
        cmbCaptain = new javax.swing.JComboBox<>();
        lblTitle21 = new javax.swing.JLabel();
        lblTitle15 = new javax.swing.JLabel();
        lblTitle17 = new javax.swing.JLabel();
        txtFlightId = new javax.swing.JTextField();
        txtDeDate = new javax.swing.JTextField();
        lblTitle4 = new javax.swing.JLabel();
        lblTitle6 = new javax.swing.JLabel();
        txtFlightType = new javax.swing.JTextField();
        lblTitle7 = new javax.swing.JLabel();
        lblTitle13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtStatusField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 149, 42));

        lblTitle8.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblTitle8.setText("Flight Information");
        add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        txtEcoNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtEcoNum.setText(flight.getRemainEco()+"");
        txtEcoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcoNumActionPerformed(evt);
            }
        });
        add(txtEcoNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 83, 30));

        txtEcoPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtEcoPrice.setText(flight.getEcoPrice() + "");
        txtEcoPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcoPriceActionPerformed(evt);
            }
        });
        add(txtEcoPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 83, 30));

        txtBusiNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtBusiNum.setText(flight.getRemainBus()+"");
        txtBusiNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusiNumActionPerformed(evt);
            }
        });
        add(txtBusiNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 83, 30));

        txtBusiPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtBusiPrice.setText(flight.getBusPrice() + "");
        txtBusiPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusiPriceActionPerformed(evt);
            }
        });
        add(txtBusiPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 83, 30));

        lblTitle18.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle18.setText("Price:");
        add(lblTitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        lblTitle19.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle19.setText("Number:");
        add(lblTitle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));

        txtFirstNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstNum.setText(flight.getRemainFirst()+"");
        txtFirstNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNumActionPerformed(evt);
            }
        });
        add(txtFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 83, 30));

        txtFirstPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstPrice.setText(flight.getFirstPrice()+"");
        txtFirstPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstPriceActionPerformed(evt);
            }
        });
        add(txtFirstPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 83, 30));

        lblTitle20.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle20.setText("Price:");
        add(lblTitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, -1, -1));

        lblTitle.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle.setText("Flight number/ID:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        lblTitle5.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle5.setText("Depature date:");
        add(lblTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle1.setText("Aircraft number/ID:");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        lblTitle9.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle9.setText("Business class:");
        add(lblTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        lblTitle14.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle14.setText("Price:");
        add(lblTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, -1, -1));

        lblTitle16.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle16.setText("Captain:");
        add(lblTitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        cmbPlaneId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbPlaneId.setModel(new DefaultComboBoxModel<>(airList));
        cmbPlaneId.setSelectedItem(flight.getAirplane() == null ? null : new BoxHelper<Airplane>(flight.getAirplane().getId(), flight.getAirplane()));
        cmbPlaneId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPlaneIdItemStateChanged(evt);
            }
        });
        add(cmbPlaneId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 257, 145, 30));

        cmbDeAirport.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbDeAirport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbDeAirport.setSelectedItem(flight.getStartAirport());
        cmbDeAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeAirportActionPerformed(evt);
            }
        });
        add(cmbDeAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 307, 145, 30));

        cmbLandAirport.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbLandAirport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbLandAirport.setSelectedItem(flight.getEndAirport());
        add(cmbLandAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 357, 145, 30));

        cmbCaptain.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbCaptain.setModel(new DefaultComboBoxModel<>(airCaptainList));
        cmbCaptain.setSelectedItem(flight.getCaptain() == null ? null : new BoxHelper<Employee>(flight.getCaptain().getId() + "", flight.getCaptain()));
        add(cmbCaptain, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 407, 145, 30));

        lblTitle21.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle21.setText("Number:");
        add(lblTitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        lblTitle15.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle15.setText("Economy class: ");
        add(lblTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        lblTitle17.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle17.setText("Number:");
        add(lblTitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        txtFlightId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFlightId.setText(flight.getId() + "");
        txtFlightId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightIdActionPerformed(evt);
            }
        });
        add(txtFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 167, 144, 30));

        txtDeDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtDeDate.setText(sdf.format(flight.getStartDate()));
        txtDeDate.setToolTipText("");
        txtDeDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeDateActionPerformed(evt);
            }
        });
        add(txtDeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 167, 30));

        lblTitle4.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle4.setText("Flight Type:");
        add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        lblTitle6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle6.setText("Departure airport:");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        txtFlightType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFlightType.setText(flight.getType());
        txtFlightType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightTypeActionPerformed(evt);
            }
        });
        add(txtFlightType, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 217, 144, 30));

        lblTitle7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle7.setText("Landing airport:");
        add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        lblTitle13.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle13.setText("First class:");
        add(lblTitle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel1.setText("Status:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        txtStatusField.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtStatusField.setText(flight.getStatus());
        add(txtStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/hiking.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, 300));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 60, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/airplane1_1.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = txtFlightId.getText();
        String type = txtFlightType.getText();
        BoxHelper<Airplane> airplane = (BoxHelper<Airplane>)cmbPlaneId.getSelectedItem();
        String deAirport = (String)cmbDeAirport.getSelectedItem();
        String laAirport = (String)cmbLandAirport.getSelectedItem();
        BoxHelper<Employee> employee = (BoxHelper<Employee>)cmbCaptain.getSelectedItem();
        int ecoSeatNumber = Integer.parseInt(txtEcoNum.getText());
        int busSeatNumber = Integer.parseInt(txtBusiNum.getText());
        int firstSeatNumber = Integer.parseInt(txtFirstNum.getText());
        double ep = Double.parseDouble(txtEcoPrice.getText());
        double bp = Double.parseDouble(txtBusiPrice.getText());
        double fp = Double.parseDouble(txtFirstPrice.getText());
        String status = txtStatusField.getText();
        Date sDate;
        try {
            sDate = sdf.parse(txtDeDate.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Depature Date format error!");
            return;
        }
        
        // check
        AirlineCompany airLineCompany = (AirlineCompany)origanization;
        List<request> requests = airLineCompany.getRequestDirectory().getRequestList();
        for (request request : requests) {
            if (request instanceof Flight) {
                Flight flight = (Flight)request;
                if (this.flight.getId() != flight.getId() && flight.getId() == Integer.parseInt(id)) {
                    JOptionPane.showMessageDialog(null, "Flight number/ID already exists!");
                    return;
                }
                if (flight.getStartDate() != null && 
                    flight.getCaptain() != null &&
                    this.flight.getId() != flight.getId() &&
                    sdf.format(sDate).substring(0, 5).equals(sdf.format(flight.getStartDate()).substring(0, 5))
                    && employee.getData().getId() == flight.getCaptain().getId()) {
                    JOptionPane.showMessageDialog(null, "The same person can only arrange one shift a day!");
                    return;
                }
                
                
            }
        }
        if (deAirport.equals(laAirport)) {
            JOptionPane.showMessageDialog(null, "Departure airport and Langding airport cannot same!");
            return;
        }
        flight.setId(Integer.parseInt(id));
        flight.setRequestPersonId(employee.getId());
        flight.setOrganizationId(origanization.getId());
        flight.setType(type);
        flight.setFlight(deAirport, laAirport, airplane.getData(), employee.getData(), 
            ecoSeatNumber, busSeatNumber, firstSeatNumber, 
            ep, bp, fp);
        flight.setStartDate(sDate);
        flight.setStatus(status);
        DB4OUtil.getInstance().storeSystem(system);
        // Information Added Succesfully!
        JOptionPane.showMessageDialog(null, "Information Added Succesfully!");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtEcoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcoNumActionPerformed

    private void txtEcoPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcoPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcoPriceActionPerformed

    private void txtBusiNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusiNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusiNumActionPerformed

    private void txtBusiPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusiPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusiPriceActionPerformed

    private void txtFirstNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNumActionPerformed

    private void txtFirstPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstPriceActionPerformed

    private void txtFlightIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightIdActionPerformed

    private void txtDeDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeDateActionPerformed

    private void txtFlightTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightTypeActionPerformed

    private void cmbDeAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeAirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDeAirportActionPerformed

    private void cmbPlaneIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPlaneIdItemStateChanged
        // TODO add your handling code here:
        BoxHelper<Airplane> helper = (BoxHelper<Airplane>)cmbPlaneId.getSelectedItem();
        if (null == helper) {
            return;
        }
        Airplane airplane = helper.getData();
        txtEcoNum.setText("" + airplane.getEcoSeatNumber());
        txtBusiNum.setText("" + airplane.getBusSeatNumber());
        txtFirstNum.setText("" + airplane.getFirstSeatNumber());
    }//GEN-LAST:event_cmbPlaneIdItemStateChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ShowFlightJPanel rwajp = new ShowFlightJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("ShowFlightJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<BoxHelper<Employee>> cmbCaptain;
    private javax.swing.JComboBox<String> cmbDeAirport;
    private javax.swing.JComboBox<String> cmbLandAirport;
    private javax.swing.JComboBox<BoxHelper<Airplane>> cmbPlaneId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle13;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle16;
    private javax.swing.JLabel lblTitle17;
    private javax.swing.JLabel lblTitle18;
    private javax.swing.JLabel lblTitle19;
    private javax.swing.JLabel lblTitle20;
    private javax.swing.JLabel lblTitle21;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JTextField txtBusiNum;
    private javax.swing.JTextField txtBusiPrice;
    private javax.swing.JTextField txtDeDate;
    private javax.swing.JTextField txtEcoNum;
    private javax.swing.JTextField txtEcoPrice;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtFirstPrice;
    private javax.swing.JTextField txtFlightId;
    private javax.swing.JTextField txtFlightType;
    private javax.swing.JTextField txtStatusField;
    // End of variables declaration//GEN-END:variables
}
