/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AirlineCompany;

import java.awt.CardLayout;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.organization.AirlineCompany;
import api.organization.Organization;
import api.property.Airplane;
import ui.AirlineCompany.*;

/**
 *
 * @author Lynn Wei
 */
public class UpdatePlaneJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private Airplane airplane;
    
    public UpdatePlaneJPanel(JPanel userProcessContainer, Employee employee, 
        TravelSystem system, Organization origanization, Airplane airplane) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        this.airplane = airplane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        lblTitle8 = new javax.swing.JLabel();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle15 = new javax.swing.JLabel();
        txtPlaneType = new javax.swing.JTextField();
        txtSeatNum = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtEcoNum = new javax.swing.JTextField();
        txtBusiNum = new javax.swing.JTextField();
        txtPlaneId = new javax.swing.JTextField();
        lblTitle18 = new javax.swing.JLabel();
        lblTitle6 = new javax.swing.JLabel();
        txtFirstNum = new javax.swing.JTextField();
        lblTitle7 = new javax.swing.JLabel();
        lblTitle20 = new javax.swing.JLabel();
        lblTitle9 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 149, 42));

        lblTitle8.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblTitle8.setText("Airplane Information");
        add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        lblTitle14.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle14.setText("Economy class seats number:");
        add(lblTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        lblTitle15.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle15.setText("Seats number:");
        add(lblTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        txtPlaneType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtPlaneType.setText(airplane.getType().toString());
        txtPlaneType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaneTypeActionPerformed(evt);
            }
        });
        add(txtPlaneType, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 167, 30));

        txtSeatNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSeatNum.setText("" + airplane.getSeatNumber());
        txtSeatNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatNumActionPerformed(evt);
            }
        });
        add(txtSeatNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 167, 30));

        lblTitle.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle.setText("Aircraft type:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        txtEcoNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtEcoNum.setText("" + airplane.getEcoSeatNumber());
        txtEcoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcoNumActionPerformed(evt);
            }
        });
        add(txtEcoNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 100, 30));

        txtBusiNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtBusiNum.setText("" + airplane.getBusSeatNumber());
        txtBusiNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusiNumActionPerformed(evt);
            }
        });
        add(txtBusiNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 100, 30));

        txtPlaneId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtPlaneId.setText(airplane.getId().toString());
        txtPlaneId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaneIdActionPerformed(evt);
            }
        });
        add(txtPlaneId, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 167, 30));

        lblTitle18.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle18.setText("Business class seats number:");
        add(lblTitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        lblTitle6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle6.setText("Aircraft number/ID:");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        txtFirstNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstNum.setText("" + airplane.getFirstSeatNumber());
        txtFirstNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNumActionPerformed(evt);
            }
        });
        add(txtFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 100, 30));

        lblTitle7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle7.setText("Year:");
        add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, -1, -1));

        lblTitle20.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle20.setText("First class seats number:");
        add(lblTitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        lblTitle9.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle9.setText("Age:");
        add(lblTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, -1));

        txtYear.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtYear.setText("" + airplane.getYear());
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 167, 30));

        txtAge.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtAge.setText("" + airplane.getAge());
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 167, 30));

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/Backbutton_3.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/girl.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 480, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/airplane3_1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String Id = txtPlaneId.getText();
        String type = txtPlaneType.getText();
        int year = Integer.parseInt(txtYear.getText());
        int age = Integer.parseInt(txtAge.getText());
        int seatNumber = Integer.parseInt(txtSeatNum.getText());
        int ecoSeatNumber = Integer.parseInt(txtEcoNum.getText());
        int busSeatNumber = Integer.parseInt(txtBusiNum.getText());
        int firstSeatNumber = Integer.parseInt(txtFirstNum.getText());
        // check 
        AirlineCompany airLineCompany = (AirlineCompany)origanization;
        List<Airplane> airplaneList = airLineCompany.getAirplaneList();
        for (Airplane airPlane : airplaneList) {
            if (!airPlane.getId().equals(airplane.getId()) && airPlane.getId().equals(Id)) {
                JOptionPane.showMessageDialog(null, "Aircraft number/ID already exists!");
                return;
            }
        }
        airplane.setId(Id);
        airplane.setType(type);
        airplane.setYear(year);
        airplane.setAge(age);
        airplane.setSeatNumber(seatNumber);
        airplane.setEcoSeatNumber(ecoSeatNumber);
        airplane.setBusSeatNumber(busSeatNumber);
        airplane.setFirstSeatNumber(firstSeatNumber);
        DB4OUtil.getInstance().storeSystem(system);
        JOptionPane.showMessageDialog(null, "Information Updated Succesfully!");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtPlaneTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaneTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlaneTypeActionPerformed

    private void txtSeatNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatNumActionPerformed

    private void txtEcoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcoNumActionPerformed

    private void txtBusiNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusiNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusiNumActionPerformed

    private void txtPlaneIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaneIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlaneIdActionPerformed

    private void txtFirstNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNumActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        ShowPlaneJPanel rwajp = new ShowPlaneJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("ShowPlaneJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle18;
    private javax.swing.JLabel lblTitle20;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBusiNum;
    private javax.swing.JTextField txtEcoNum;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtPlaneId;
    private javax.swing.JTextField txtPlaneType;
    private javax.swing.JTextField txtSeatNum;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
