/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerRole;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import business.DB4OUtil.DB4OUtil;
import business.DB4OUtil.RestaurantMenuDBUtil;
import business.DB4OUtil.UserDBUtil;
import business.dto.OrderDto;
import business.dto.RestaurantMenuDto;
import business.dto.UserDto;
import business.type.OrganizationType;

/**
 *
 * @author raunak
 */
public class OrderMealJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    
    private final UserDto userDto;
    
    private OrderDto selectedOrderDto;
    
    /**
     * Creates new form RequestLabTestJPanel
     */
    public OrderMealJPanel(JPanel userProcessContainer, UserDto userDto) {
        this.userProcessContainer = userProcessContainer;
        this.userDto = userDto;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 50));

        jLabel1.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        jLabel1.setText("Restaurant:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        // get restaurant name
        List<UserDto> userList = UserDBUtil.queryByOrg(OrganizationType.Restaurant.getValue());
        UserDto[] array = new UserDto[userList.size()];
        for (int i = 0; i < array.length; i++) {
            array[i] = userList.get(i);
        }
        DefaultComboBoxModel<UserDto> model = new DefaultComboBoxModel<>(array);
        jComboBox1.setModel(model);
        jComboBox1.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    // 清空已有列表
                    DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
                    int size = model.getRowCount();
                    for (int i = 0; i < size; i++) {
                        model.removeRow(0);
                    }
                    // 选择的下拉框选项
                    UserDto userDto = (UserDto)e.getItem();
                    List<RestaurantMenuDto> list = RestaurantMenuDBUtil.queryByRelId(userDto.getId());
                    for (RestaurantMenuDto menuDto : list) {
                        Object[] row = new Object[4];
                        row[0] = userDto.getRestaurantName();
                        row[1] = menuDto.getMeal();
                        row[2] = menuDto.getPrice();
                        row[3] = menuDto.getId();
                        model.addRow(row);
                    }
                }
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 160, -1));

        // 添加默认选项
        Object[][] dataList = new Object[userList.size()][4];
        if (userList.size() > 0) {
            UserDto userDto = userList.get(0);
            List<RestaurantMenuDto> list = RestaurantMenuDBUtil.queryByRelId(userDto.getId());
            for (int i = 0; i < list.size(); i++) {
                dataList[i][0] = userDto.getRestaurantName();
                dataList[i][1] = list.get(i).getMeal();
                dataList[i][2] = list.get(i).getPrice();
                dataList[i][3] = list.get(i).getId();
            }
        }
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            dataList,
            new String [] {
                "Restaurant", "Meal", "Price", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(30);
        jScrollPane1.setViewportView(workRequestJTable);
        TableColumn tc = workRequestJTable.getTableHeader().getColumnModel().getColumn(3);
        tc.setMaxWidth(0);
        tc.setWidth(0);
        tc.setMinWidth(0);
        workRequestJTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    return;
                }
                int i = workRequestJTable.getSelectedRow();
                if (i < 0) {
                    return;
                }
                // String id = (String)workRequestJTable.getValueAt(i, 3);
                String restName = (String)workRequestJTable.getValueAt(i, 0);
                String meal = (String)workRequestJTable.getValueAt(i, 1);
                selectedOrderDto = new OrderDto(restName, meal, "", userDto.getUserName(), "ordered", "");
            }
        });
        
        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 720, 270));

        requestTestJButton.setText("Order Meal");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAreaJPanel dwjp = (CustomerAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        if (null == selectedOrderDto) {
            return;
        }
        DB4OUtil.getInstance().storeSystem(selectedOrderDto);
        selectedOrderDto = null;
        JOptionPane.showMessageDialog(null, "Order menu successfully.");
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<UserDto> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
