/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RestaurantRole;

import java.util.List;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import business.DB4OUtil.OrderDBUtil;
import business.DB4OUtil.UserDBUtil;
import business.dto.OrderDto;
import business.dto.UserDto;
import business.type.OrganizationType;

/**
 *
 * @author Lynn Wei
 */
public class ManageOrderJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    
    private UserDto userDto;
    /**
     * Creates new form ManageInfoJPanel
     */
    public ManageOrderJPanel(javax.swing.JPanel userProcessContainer, UserDto userDto) {
        this.userDto = userDto;
        this.userProcessContainer = userProcessContainer;
        initComponents();
        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        int size = model.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
        List<OrderDto> orderList = OrderDBUtil.queryByRestName(this.userDto.getRestaurantName());
        JComboBox<String> c = new JComboBox<>();
        // get all del
        List<UserDto> userList = UserDBUtil.queryByOrg(OrganizationType.Delivery.getValue());
        for (UserDto userDto : userList) {
            c.addItem(userDto.getUserName());
        }
        for (int i = 0; i < orderList.size(); i++) {
            Object[] data = new Object[5];
            data[0] = orderList.get(i).getMeal();
            data[1] = orderList.get(i).getUserName();
            data[2] = orderList.get(i).getDeliveryName();
            data[3] = orderList.get(i).getStatus();
            data[4] = orderList.get(i).getId();
            model.addRow(data);
        }
        workRequestJTable.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(c));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lblTitle.setText("Manage Orders");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        enterpriseLabel.setText("Restaurant :");

        valueLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        valueLabel.setText(this.userDto.getRestaurantName());

        jButton2.setText("Accept Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Meal", "Customer UserName", "Deliveryman UserName", "Status", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, 
                java.lang.String.class, 
                java.lang.String.class, 
                java.lang.String.class,
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                // get this line data
                if (columnIndex == 2) {
                    String status = (String)workRequestJTable.getModel().getValueAt(rowIndex, 3);
                    if (status.equals("ordered")) {
                        return true;
                    } else {
                        return false;
                    }
                }
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(35);
        TableColumn tc = workRequestJTable.getTableHeader().getColumnModel().getColumn(4);
        tc.setMaxWidth(0);
        tc.setWidth(0);
        tc.setMinWidth(0);
        jScrollPane2.setViewportView(workRequestJTable);

        jButton3.setText("Reject Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(valueLabel)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // add your handling code here:
        int i = workRequestJTable.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a line.");
            return;
        }
        String delName = (String)workRequestJTable.getModel().getValueAt(i, 2);
        if (delName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a deliveryman.");
            return;
        }
        String id = (String)workRequestJTable.getModel().getValueAt(i, 4);
        OrderDto orderDto = OrderDBUtil.queryById(id);
        if (!orderDto.getStatus().equals("ordered")) {
            return;
        }
        orderDto.setDeliveryName(delName);
        orderDto.setStatus("Pending");
        OrderDBUtil.update(orderDto);
        workRequestJTable.getModel().setValueAt("Pending", i, 3);
        JOptionPane.showMessageDialog(null, "Accept order is success.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // add your handling code here:
        int i = workRequestJTable.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a line.");
            return;
        }
        String id = (String)workRequestJTable.getModel().getValueAt(i, 4);
        OrderDto orderDto = OrderDBUtil.queryById(id);
        if (!orderDto.getStatus().equals("ordered")) {
            return;
        }
        orderDto.setDeliveryName("");
        orderDto.setStatus("Rejected");
        OrderDBUtil.update(orderDto);
        workRequestJTable.getModel().setValueAt("Rejected", i, 3);
        JOptionPane.showMessageDialog(null, "Rejected order is success.");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
