/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RestaurantRole;

import java.awt.CardLayout;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import business.DB4OUtil.DB4OUtil;
import business.DB4OUtil.RestaurantMenuDBUtil;
import business.dto.RestaurantMenuDto;
import business.dto.UserDto;

/**
 *
 * @author Lynn Wei
 */
public class ManageMenuJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private UserDto userDto;
    
    private RestaurantMenuDto selectedMenuDto;
    
    private int rowIndex = -1;

    /**
     * Creates new form ManageMenuJPanel
     */
    public ManageMenuJPanel(javax.swing.JPanel userProcessContainer, UserDto userDto) {
        this.userDto = userDto;
        this.userProcessContainer=userProcessContainer;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtMeal = new javax.swing.JTextField();
        lblMeal = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lblTitle.setText("Manage Menu");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        enterpriseLabel.setText("Restaurant :");

        valueLabel.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        valueLabel.setText(this.userDto.getRestaurantName());

        btnBack.setText(">>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblMeal.setText("Meal:");

        lblPrice.setText("Price:");

        List<RestaurantMenuDto> list = RestaurantMenuDBUtil.queryByRelId(userDto.getId());
        Object[][] dataList = new Object[list.size()][3];
        for (int i = 0; i < dataList.length; i++) {
            dataList[i][0] = list.get(i).getMeal();
            dataList[i][1] = list.get(i).getPrice();
            dataList[i][2] = list.get(i).getId();
        }
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            dataList,
            new String [] {
                "Meal Menu", "Price", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblUsers);
        tblUsers.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    return;
                }
                int i = tblUsers.getSelectedRow();
                if (i < 0) {
                    return;
                }
                String id = (String)tblUsers.getValueAt(i, 2);
                RestaurantMenuDto resMenuDto = RestaurantMenuDBUtil.queryById(id);
                txtMeal.setText(resMenuDto.getMeal());
                txtPrice.setText(resMenuDto.getPrice());
                selectedMenuDto = resMenuDto;
                rowIndex = i;
            }
        });
        // ����������
        TableColumn tc = tblUsers.getTableHeader().getColumnModel().getColumn(2);
        tc.setMaxWidth(0);
        tc.setWidth(0);
        tc.setMinWidth(0);
        
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCreate.setText("Add");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(valueLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblMeal)
                                                .addGap(27, 27, 27)
                                                .addComponent(txtMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPrice)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMeal)
                            .addComponent(txtMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrice)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        RestaurantMenuDto menuDto = RestaurantMenuDBUtil.queryById(selectedMenuDto.getId());
        RestaurantMenuDBUtil.remove(menuDto);
        model.removeRow(rowIndex);
        txtMeal.setText("");
        txtPrice.setText("");
        selectedMenuDto = null;
        rowIndex = -1;
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // add your handling code here:
        String meal = txtMeal.getText();
        String price = txtPrice.getText();
        if (meal.isEmpty() || price.isEmpty()) {
            return;
        }
        // ��ȡԭ�ж���
        selectedMenuDto.setMeal(meal);
        selectedMenuDto.setPrice(price);
        // ����
        RestaurantMenuDBUtil.update(selectedMenuDto);
        tblUsers.getModel().setValueAt(selectedMenuDto.getMeal(), rowIndex, 0);
        tblUsers.getModel().setValueAt(selectedMenuDto.getPrice(), rowIndex, 1);
        JOptionPane.showMessageDialog(null, "Menu updated successfully.");
        txtMeal.setText("");
        txtPrice.setText("");
        selectedMenuDto = null;
        rowIndex = -1;
        rowIndex = -1;
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String meal = txtMeal.getText();
        String price = txtPrice.getText();
        if (meal.isEmpty() || price.isEmpty()) {
            return;
        }
        RestaurantMenuDto menuDto = new RestaurantMenuDto(this.userDto.getId(), meal, price);
        DB4OUtil.getInstance().storeSystem(menuDto);
        
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        Object[] row = new Object[3];
        row[0] = menuDto.getMeal();
        row[1] = menuDto.getPrice();
        row[2] = menuDto.getId();
        model.addRow(row);

        txtMeal.setText("");
        txtPrice.setText("");
        selectedMenuDto = null;
        rowIndex = -1;
        // JOptionPane.showMessageDialog(this, "Sorry，please enter a valid value."+validStr);
        JOptionPane.showMessageDialog(null, "New Meal added successfully", "successfully", JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // add your handling code here:
        ResaurantWorkAreaJPanel rwajp = new ResaurantWorkAreaJPanel(userProcessContainer, this.userDto);
        userProcessContainer.add("ResaurantWorkAreaJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMeal;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtMeal;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
