/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerService;

import api.TravelSystem;
import api.employee.Employee;
import api.organization.Organization;
import api.request.VIPComment;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;

/**
 *
 * @author Lynn Wei
 */
public class CommentVIPJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization organization;
    private VIPComment vipComment;
    private SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");

    /**
     * Creates new form CommentDetailJPanel
     */
    public CommentVIPJPanel(JPanel userProcessContainer, Employee employee, TravelSystem system, Organization organization, VIPComment vipComment ) {
        this.system = system;
        this.employee = employee;
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        this.vipComment = vipComment;
        initComponents();
        
        txtRequestPersonId.setEditable(false);
        txtOrganizationId.setEditable(false);
        txtType.setEditable(false);
        txtComment.setEditable(false);
        txtStatus.setEditable(false);
        txtId.setEditable(false);
        txtStartDate.setEditable(false);
        txtendDate.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblComment = new javax.swing.JLabel();
        lblRequestPersonId = new javax.swing.JLabel();
        txtRequestPersonId = new javax.swing.JTextField();
        txtOrganizationId = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        lblOrganizationId = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        lblstartDate = new javax.swing.JLabel();
        lblendDate = new javax.swing.JLabel();
        txtendDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblId.setText("Id:");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 39, 23));

        lblComment.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblComment.setText("Comment:");
        add(lblComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 85, 37));

        lblRequestPersonId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblRequestPersonId.setText("Request Person Id:");
        add(lblRequestPersonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 52));

        txtRequestPersonId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtRequestPersonId.setText(vipComment.getRequestPersonId());
        txtRequestPersonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRequestPersonIdActionPerformed(evt);
            }
        });
        add(txtRequestPersonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 159, 166, -1));

        txtOrganizationId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtOrganizationId.setText(vipComment.getOrganizationId());
        add(txtOrganizationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 226, 166, -1));

        lblType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblType.setText("Type:");
        add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 294, -1, 27));

        txtComment.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtComment.setText(vipComment.getComment());
        add(txtComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 368, 205, 101));

        txtType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtType.setText(vipComment.getType());
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 294, 166, -1));

        lblOrganizationId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblOrganizationId.setText("Organization Id:");
        add(lblOrganizationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 152, 52));

        lblTitle.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle.setText("VIP Customer Comment");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 36, 622, 82));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/CustomerService/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 39, 60, 44));

        txtId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtId.setText(vipComment.getId()+"");
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 166, -1));

        lblStatus.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblStatus.setText("Status:");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, 27));

        txtStatus.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtStatus.setText(vipComment.getStatus());
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 166, -1));

        txtStartDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtStartDate.setText(sdf.format(vipComment.getStartDate()));
        add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 166, -1));

        lblstartDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblstartDate.setText("Start Date:");
        add(lblstartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, 27));

        lblendDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblendDate.setText("End Date:");
        add(lblendDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, 27));

        txtendDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtendDate.setText(vipComment.getEndDate() == null ? "" : sdf.format(vipComment.getEndDate()));
        add(txtendDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 166, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/CustomerService/service5.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 540, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/CustomerService/customer_副本.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 400, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRequestPersonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequestPersonIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequestPersonIdActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:\
        VIPCustomerServicePanel showPlaneJPanel = new VIPCustomerServicePanel(userProcessContainer, employee, system, organization);
        userProcessContainer.add("VIPCustomerServicePanel", showPlaneJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblOrganizationId;
    private javax.swing.JLabel lblRequestPersonId;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblendDate;
    private javax.swing.JLabel lblstartDate;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtOrganizationId;
    private javax.swing.JTextField txtRequestPersonId;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtendDate;
    // End of variables declaration//GEN-END:variables
}
