/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerService;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.organization.AirlineCompany;
import api.organization.Organization;
import api.organization.RailwayCompany;
import api.request.Flight;
import api.request.FlightTicket;
import api.request.TrainLine;
import api.request.TrainTicket;
import api.request.request;
import api.userAccount.UserAccount;
import java.util.ArrayList;

/**
 *
 * @author 10857
 */
public class CustomerServicePanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private List<request> ticketRequests = new ArrayList<>();
    
    public CustomerServicePanel(UserAccount user,Employee em,TravelSystem system, Organization o) {
        initComponents();
        this.system = system;
        this.employee = em;
        this.origanization = o;
    }
    
    public CustomerServicePanel(JPanel userProcessContainer, Employee employee, TravelSystem system, Organization origanization) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        initComponents();
        populateRequestTable();
    }
    
    
    private void populateRequestTable(){
        // TrainTicket
        if (origanization instanceof AirlineCompany) {
            addInitRowData("FlightTicket");
        } else if (origanization instanceof RailwayCompany) {
            addInitRowData("TrainTicket");
        }
    }
    
    private void initRequest(String type) {
        List<UserAccount> userAccountList = origanization.getUserAccountDirectory().getUserAccountList();
        for (UserAccount userAccount : userAccountList) {
            if (!userAccount.getRole().getRole().equals("Customer")) {
                continue;
            }
        
            List<request> requests = userAccount.getRequestDirectory().getRequestList();
            for (request request : requests) {
                // "Id", "requestPersonId", "Type", "Status", "endDate"
//                   if (!"Finished".equals(request.getStatus()) || !request.getType().startsWith(type)) {
//                      continue;
//                  }
                if(!request.getType().startsWith(type)){
                    continue;
                }
                ticketRequests.add(request);
            }
        }
    }
    
    private void addInitRowData(String type) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int size = model.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
        initRequest(type);
        for (request request : ticketRequests) {
            Object[] row = new Object[5];
            row[0] = request.getId();
            row[1] = request.getRequestPersonId();
            row[2] = request.getType();
            row[3] = request.getStatus();
            SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
            row[4] = request.getEndDate() == null ? "" : sdf.format(request.getEndDate());
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblCompany = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        btnTicketsDetail = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle.setText(" Customer Service");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jTable1.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Request Person Id", "Type", "Status", "End Date"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 790, 280));

        lblCompany.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblCompany.setText(origanization.getName());
        add(lblCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 408, 50));

        lblTitle1.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle1.setText("Service Company:");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 94, -1, -1));

        btnTicketsDetail.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnTicketsDetail.setText("Tickets Details");
        btnTicketsDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsDetailActionPerformed(evt);
            }
        });
        add(btnTicketsDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 191, -1));

        btnProcess.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 191, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/CustomerService/service2_2_副本.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 350, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTicketsDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsDetailActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        if (origanization instanceof AirlineCompany) {
            DetailAirCustomerJPanel showPlaneJPanel = new DetailAirCustomerJPanel(userProcessContainer, employee, system, origanization,
                (FlightTicket)ticketRequests.get(i));
            userProcessContainer.add("DetailAirCustomerJPanel", showPlaneJPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else if (origanization instanceof RailwayCompany) {
            DetailTrainCustomerJPanel showPlaneJPanel = new DetailTrainCustomerJPanel(userProcessContainer, employee, system, origanization,
                (TrainTicket)ticketRequests.get(i));
            userProcessContainer.add("DetailTrainCustomerJPanel", showPlaneJPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnTicketsDetailActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }

        request request = ticketRequests.get(i);
        SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
        Date now = new Date();
        request.setEndDate(now);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt(sdf.format(now), i, 4);
        DB4OUtil.getInstance().storeSystem(system);
        JOptionPane.showMessageDialog(null, "Information Process Succesfully!");
    }//GEN-LAST:event_btnProcessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnTicketsDetail;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
