/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerService;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import api.BoxHelper;
import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.enterprise.Enterprise;
import api.organization.AirlineCompany;
import api.organization.Airport;
import api.organization.Organization;
import api.property.Airplane;
import api.request.Flight;
import api.request.request;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Lynn Wei
 */
public class FlightRequestJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private Flight flight;
    private BoxHelper<Airplane>[] airList = new BoxHelper[0];
    private BoxHelper<Airport>[] airportList = new BoxHelper[0];
    private BoxHelper<Employee>[] airCaptainList = new BoxHelper[0];
    private SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
    
    public FlightRequestJPanel(JPanel userProcessContainer, Employee employee, 
        TravelSystem system, Organization origanization, Flight flight) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        this.flight = flight;
        AirlineCompany airLineCompany = (AirlineCompany)origanization;
        List<Airplane> airplaneList = airLineCompany.getAirplaneList();
        airList = new BoxHelper[airplaneList.size()];
        for (int i = 0; i < airList.length; i++) {
            airList[i] = new BoxHelper<>(airplaneList.get(i).getId(), airplaneList.get(i));
        }
        
        // Airport
        getAirPortList();
        getEmployeeList();
        initComponents();
        
        txtFlightId.setEditable(false);
        txtFlightType.setEditable(false);
        cmbDeAirport.setEditable(false);
        cmbLandAirport.setEditable(false);
        cmbPlaneId.setEditable(false);
        cmbCaptain.setEditable(false);
        txtDeDate.setEditable(false);
        txtEcoNum.setEditable(false);
        txtEcoPrice.setEditable(false);
        txtBusiNum.setEditable(false);
        txtBusiPrice.setEditable(false);
        txtFirstNum.setEditable(false);
        txtFirstPrice.setEditable(false);
        txtStatusField.setEditable(false);
        
    }
    
    private void getAirPortList() {
        ArrayList<Enterprise> enterpriseList = system.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise enterprise : enterpriseList) {
            if (enterprise.getName().equals("Airport")) {
                List<Organization> orgList = enterprise.getOrganizationDirectory().getOrganizationList();
                airportList = new BoxHelper[orgList.size()];
                for (int i = 0; i < orgList.size(); i++) {
                    Airport airport = (Airport)orgList.get(i);
                    airportList[i] = new BoxHelper<>(airport.getId(), airport);
                }
            }
        }
    }
    
    private void getEmployeeList() {
        AirlineCompany airLineCompany = (AirlineCompany)origanization;
        List<Employee> employeeList = new ArrayList<>();
        for (Employee employee : airLineCompany.getEmployeeDirectory().getEmployeeList()) {
            if (employee.getRole().getRole().equals("AirCaptain")) {
                employeeList.add(employee);
            }
        }
        airCaptainList = new BoxHelper[employeeList.size()];
        for (int i = 0; i < employeeList.size(); i++) {
            airCaptainList[i] = new BoxHelper<>(employeeList.get(i).getName(), employeeList.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle8 = new javax.swing.JLabel();
        txtEcoNum = new javax.swing.JTextField();
        txtEcoPrice = new javax.swing.JTextField();
        txtBusiNum = new javax.swing.JTextField();
        txtBusiPrice = new javax.swing.JTextField();
        lblTitle18 = new javax.swing.JLabel();
        lblTitle19 = new javax.swing.JLabel();
        txtFirstNum = new javax.swing.JTextField();
        txtFirstPrice = new javax.swing.JTextField();
        lblTitle20 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle9 = new javax.swing.JLabel();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle16 = new javax.swing.JLabel();
        cmbPlaneId = new javax.swing.JComboBox<>();
        cmbDeAirport = new javax.swing.JComboBox<>();
        cmbLandAirport = new javax.swing.JComboBox<>();
        cmbCaptain = new javax.swing.JComboBox<>();
        lblTitle21 = new javax.swing.JLabel();
        lblTitle15 = new javax.swing.JLabel();
        lblTitle17 = new javax.swing.JLabel();
        txtFlightId = new javax.swing.JTextField();
        txtDeDate = new javax.swing.JTextField();
        lblTitle4 = new javax.swing.JLabel();
        lblTitle6 = new javax.swing.JLabel();
        txtFlightType = new javax.swing.JTextField();
        lblTitle7 = new javax.swing.JLabel();
        lblTitle13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtStatusField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/CustomerService/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 60));

        lblTitle8.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle8.setText("Flight Information");
        add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        txtEcoNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtEcoNum.setText(flight.getRemainEco()+"");
        add(txtEcoNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 83, 30));

        txtEcoPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtEcoPrice.setText(flight.getEcoPrice() + "");
        add(txtEcoPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 83, 30));

        txtBusiNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtBusiNum.setText(flight.getRemainBus()+"");
        add(txtBusiNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 83, 30));

        txtBusiPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtBusiPrice.setText(flight.getBusPrice() + "");
        add(txtBusiPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 83, 30));

        lblTitle18.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle18.setText("Price:");
        add(lblTitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, -1, -1));

        lblTitle19.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle19.setText("Number:");
        add(lblTitle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        txtFirstNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstNum.setText(flight.getRemainFirst()+"");
        add(txtFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 83, 30));

        txtFirstPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstPrice.setText(flight.getFirstPrice()+"");
        add(txtFirstPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 83, 30));

        lblTitle20.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle20.setText("Price:");
        add(lblTitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, -1, -1));

        lblTitle.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle.setText("Flight number/ID:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        lblTitle5.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle5.setText("Depature date:");
        add(lblTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle1.setText("Aircraft number/ID:");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        lblTitle9.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle9.setText("Business class:");
        add(lblTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, -1));

        lblTitle14.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle14.setText("Price:");
        add(lblTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, -1, -1));

        lblTitle16.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle16.setText("Captain:");
        add(lblTitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        cmbPlaneId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbPlaneId.setModel(new DefaultComboBoxModel<>(airList));
        cmbPlaneId.setSelectedItem(flight.getAirplane()==null ? null : new BoxHelper<Airplane>(flight.getAirplane().getId(), flight.getAirplane()));
        cmbPlaneId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlaneIdActionPerformed(evt);
            }
        });
        add(cmbPlaneId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 145, 30));

        cmbDeAirport.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbDeAirport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbDeAirport.setSelectedItem(new BoxHelper<Airport>(flight.getStartAirport(), null));
        add(cmbDeAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 145, 30));

        cmbLandAirport.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbLandAirport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbLandAirport.setSelectedItem(new BoxHelper<Airport>(flight.getEndAirport(), null));
        add(cmbLandAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 145, 30));

        cmbCaptain.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbCaptain.setModel(new DefaultComboBoxModel<>(airCaptainList));
        cmbCaptain.setSelectedItem(flight.getCaptain()==null? null:new BoxHelper<Employee>(flight.getCaptain().getId() + "", flight.getCaptain()));
        cmbCaptain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCaptainActionPerformed(evt);
            }
        });
        add(cmbCaptain, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 145, 30));

        lblTitle21.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle21.setText("Number:");
        add(lblTitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        lblTitle15.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle15.setText("Economy class: ");
        add(lblTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        lblTitle17.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle17.setText("Number:");
        add(lblTitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, -1));

        txtFlightId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFlightId.setText(flight.getId() + "");
        add(txtFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 144, 30));

        txtDeDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtDeDate.setText(sdf.format(flight.getStartDate()));
        txtDeDate.setToolTipText("");
        add(txtDeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 167, 30));

        lblTitle4.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle4.setText("Flight Type:");
        add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        lblTitle6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle6.setText("Departure airport:");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        txtFlightType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFlightType.setText(flight.getType());
        add(txtFlightType, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 144, 30));

        lblTitle7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle7.setText("Landing airport:");
        add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        lblTitle13.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle13.setText("First class:");
        add(lblTitle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel1.setText("Status:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        txtStatusField.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtStatusField.setText(flight.getStatus());
        add(txtStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/CustomerService/service1_2.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 590, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        VIPCustomerServicePanel rwajp = new VIPCustomerServicePanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("VIPCustomerServicePanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbCaptainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCaptainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCaptainActionPerformed

    private void cmbPlaneIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlaneIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPlaneIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<BoxHelper<Employee>> cmbCaptain;
    private javax.swing.JComboBox<String> cmbDeAirport;
    private javax.swing.JComboBox<String> cmbLandAirport;
    private javax.swing.JComboBox<BoxHelper<Airplane>> cmbPlaneId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle13;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle16;
    private javax.swing.JLabel lblTitle17;
    private javax.swing.JLabel lblTitle18;
    private javax.swing.JLabel lblTitle19;
    private javax.swing.JLabel lblTitle20;
    private javax.swing.JLabel lblTitle21;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JTextField txtBusiNum;
    private javax.swing.JTextField txtBusiPrice;
    private javax.swing.JTextField txtDeDate;
    private javax.swing.JTextField txtEcoNum;
    private javax.swing.JTextField txtEcoPrice;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtFirstPrice;
    private javax.swing.JTextField txtFlightId;
    private javax.swing.JTextField txtFlightType;
    private javax.swing.JTextField txtStatusField;
    // End of variables declaration//GEN-END:variables
}
