/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CustomerService;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import api.BoxHelper;
import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.enterprise.Enterprise;
import api.organization.Organization;
import api.organization.RailwayCompany;
import api.organization.Station;
import api.property.Train;
import api.request.TrainLine;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Lynn Wei
 */
public class TrainRequestJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private TrainLine trainLine;
    private BoxHelper<Train>[] trains = new BoxHelper[0];
    private BoxHelper<Station>[] stations = new BoxHelper[0];
    private BoxHelper<Employee>[] trainCaptains = new BoxHelper[0];
    private SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
    
    public TrainRequestJPanel(JPanel userProcessContainer, Employee employee, 
        TravelSystem system, Organization origanization, TrainLine trainLine) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        this.trainLine = trainLine;
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<Train> trainList = railwayCompany.getTrainList();
        trains = new BoxHelper[trainList.size()];
        for (int i = 0; i < trains.length; i++) {
            trains[i] = new BoxHelper<>(trainList.get(i).getId(), trainList.get(i));
        }
        getStageList();
        getEmployeeList();
        initComponents();
        
        txtRouteNum.setEditable(false);
        txtRouteType.setEditable(false);
        cmbTrainId.setEditable(false);
        cmbDeStation.setEditable(false);
        cmbLandStation.setEditable(false);
        cmbConductor.setEditable(false);
        txtDeDate.setEditable(false);
        txtSecondNum.setEditable(false);
        txtSecondPrice.setEditable(false);
        txtFirstNum.setEditable(false);
        txtFirstPrice.setEditable(false);
        txtSleeperNum.setEditable(false);
        txtSleepPrice.setEditable(false);
        txtFirstSleepNum.setEditable(false);
        txtFirstSleepPrice.setEditable(false);
        txtStatusField.setEditable(false);
    }
    
    private void getStageList() {
        ArrayList<Enterprise> enterpriseList = system.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise enterprise : enterpriseList) {
            if (enterprise.getName().equals("Station")) {
                List<Organization> orgList = enterprise.getOrganizationDirectory().getOrganizationList();
                stations = new BoxHelper[orgList.size()];
                for (int i = 0; i < orgList.size(); i++) {
                    Station station = (Station)orgList.get(i);
                    stations[i] = new BoxHelper<>(station.getId(), station);
                }
            }
        }
    }
    
    private void getEmployeeList() {
        RailwayCompany railway = (RailwayCompany)origanization;
        List<Employee> employeeList = new ArrayList<>();
        for (Employee employee : railway.getEmployeeDirectory().getEmployeeList()) {
            if (employee.getRole().getRole().equals("TrainCaptain")) {
                employeeList.add(employee);
            }
        }
        trainCaptains = new BoxHelper[employeeList.size()];
        for (int i = 0; i < employeeList.size(); i++) {
            trainCaptains[i] = new BoxHelper<>(employeeList.get(i).getName(), employeeList.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle8 = new javax.swing.JLabel();
        lblTitle21 = new javax.swing.JLabel();
        txtBusi = new javax.swing.JLabel();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle16 = new javax.swing.JLabel();
        cmbTrainId = new javax.swing.JComboBox<>();
        cmbDeStation = new javax.swing.JComboBox<>();
        cmbLandStation = new javax.swing.JComboBox<>();
        cmbConductor = new javax.swing.JComboBox<>();
        txtRouteNum = new javax.swing.JTextField();
        lblTitle4 = new javax.swing.JLabel();
        txtRouteType = new javax.swing.JTextField();
        lblTitle22 = new javax.swing.JLabel();
        lblTitle15 = new javax.swing.JLabel();
        lblTitle17 = new javax.swing.JLabel();
        txtSecondPrice = new javax.swing.JTextField();
        txtDeDate = new javax.swing.JTextField();
        txtFirstNum = new javax.swing.JTextField();
        lblTitle23 = new javax.swing.JLabel();
        lblTitle6 = new javax.swing.JLabel();
        txtFirstPrice = new javax.swing.JTextField();
        txtFirstSleepNum = new javax.swing.JTextField();
        lblTitle7 = new javax.swing.JLabel();
        lblTitle18 = new javax.swing.JLabel();
        txtFirstSleepPrice = new javax.swing.JTextField();
        lblTitle13 = new javax.swing.JLabel();
        lblTitle19 = new javax.swing.JLabel();
        lblTitle24 = new javax.swing.JLabel();
        txtSleeperNum = new javax.swing.JTextField();
        txtSecondNum = new javax.swing.JTextField();
        txtSleepPrice = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblTitle20 = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtStatusField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle8.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle8.setText("Route Information");
        add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        lblTitle21.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle21.setText("Number:");
        add(lblTitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        txtBusi.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtBusi.setText("First class:");
        add(txtBusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        lblTitle14.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle14.setText("Price:");
        add(lblTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        lblTitle16.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle16.setText("Conductor:");
        add(lblTitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        cmbTrainId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbTrainId.setModel(new DefaultComboBoxModel<>(trains));
        cmbTrainId.setSelectedItem(trainLine.getTrain()==null ? null : new BoxHelper<Train>(trainLine.getTrain().getId()+"", trainLine.getTrain()));
        add(cmbTrainId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 145, 30));

        cmbDeStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbDeStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbDeStation.setSelectedItem(new BoxHelper<Station>(trainLine.getStationList().get(0), null));
        add(cmbDeStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 145, 30));

        cmbLandStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbLandStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbLandStation.setSelectedItem(trainLine.getStationList().size() > 2 ? trainLine.getStationList().get(2) : trainLine.getStationList().get(1));
        add(cmbLandStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 145, 30));

        cmbConductor.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbConductor.setModel(new DefaultComboBoxModel<>(trainCaptains));
        cmbConductor.setSelectedItem(trainLine.getCaptain()==null ? null :new BoxHelper<Employee>(trainLine.getCaptain().getId()+"", trainLine.getCaptain()));
        cmbConductor.setToolTipText("");
        add(cmbConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 145, 30));

        txtRouteNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtRouteNum.setText(trainLine.getId()+"");
        add(txtRouteNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 144, 30));

        lblTitle4.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle4.setText("Route Type:");
        add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        txtRouteType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtRouteType.setText(trainLine.getType());
        add(txtRouteType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 144, 30));

        lblTitle22.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle22.setText("Number:");
        add(lblTitle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        lblTitle15.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle15.setText("Second class: ");
        add(lblTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        lblTitle17.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle17.setText("Number:");
        add(lblTitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        txtSecondPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSecondPrice.setText(trainLine.getSecondSeatPrice()+"");
        add(txtSecondPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 83, 30));

        txtDeDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtDeDate.setText(sdf.format(trainLine.getStartDate()));
        add(txtDeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 167, 30));

        txtFirstNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstNum.setText(trainLine.getRemainFirstSeat()+"");
        add(txtFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 83, 30));

        lblTitle23.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle23.setText("First Sleeper class:");
        add(lblTitle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        lblTitle6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle6.setText("Departure station:");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        txtFirstPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstPrice.setText(trainLine.getFirstSeatPrice()+"");
        add(txtFirstPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 83, 30));

        txtFirstSleepNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstSleepNum.setText(trainLine.getRemainFirstSleeper()+"");
        add(txtFirstSleepNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 83, 30));

        lblTitle7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle7.setText("Landing station:");
        add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        lblTitle18.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle18.setText("Price:");
        add(lblTitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, -1, -1));

        txtFirstSleepPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstSleepPrice.setText(trainLine.getFirstSleeperPrice()+"");
        add(txtFirstSleepPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 83, 30));

        lblTitle13.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle13.setText("Sleeper class:");
        add(lblTitle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        lblTitle19.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle19.setText("Number:");
        add(lblTitle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        lblTitle24.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle24.setText("Price:");
        add(lblTitle24, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, -1, -1));

        txtSleeperNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSleeperNum.setText(trainLine.getRemainSleeper()+"");
        add(txtSleeperNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 83, 30));

        txtSecondNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSecondNum.setText(trainLine.getRemainSecondSeat()+"");
        add(txtSecondNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 83, 30));

        txtSleepPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSleepPrice.setText(trainLine.getSleeperPrice()+"");
        txtSleepPrice.setToolTipText("");
        add(txtSleepPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 83, 30));

        lblTitle.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle.setText("Route number/ID:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        lblTitle20.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle20.setText("Price:");
        add(lblTitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, -1));

        lblTitle5.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle5.setText("Depature date:");
        add(lblTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle1.setText("Train number/ID:");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel1.setText("Status:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        txtStatusField.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtStatusField.setText(trainLine.getStatus());
        add(txtStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 140, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/CustomerService/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/CustomerService/service4.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 560, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VIPCustomerServicePanel showPlaneJPanel = new VIPCustomerServicePanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("VIPCustomerServicePanel", showPlaneJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        VIPCustomerServicePanel rwajp = new VIPCustomerServicePanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("VIPCustomerServicePanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<BoxHelper<Employee>> cmbConductor;
    private javax.swing.JComboBox<String> cmbDeStation;
    private javax.swing.JComboBox<String> cmbLandStation;
    private javax.swing.JComboBox<BoxHelper<Train>> cmbTrainId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle13;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle16;
    private javax.swing.JLabel lblTitle17;
    private javax.swing.JLabel lblTitle18;
    private javax.swing.JLabel lblTitle19;
    private javax.swing.JLabel lblTitle20;
    private javax.swing.JLabel lblTitle21;
    private javax.swing.JLabel lblTitle22;
    private javax.swing.JLabel lblTitle23;
    private javax.swing.JLabel lblTitle24;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel txtBusi;
    private javax.swing.JTextField txtDeDate;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtFirstPrice;
    private javax.swing.JTextField txtFirstSleepNum;
    private javax.swing.JTextField txtFirstSleepPrice;
    private javax.swing.JTextField txtRouteNum;
    private javax.swing.JTextField txtRouteType;
    private javax.swing.JTextField txtSecondNum;
    private javax.swing.JTextField txtSecondPrice;
    private javax.swing.JTextField txtSleepPrice;
    private javax.swing.JTextField txtSleeperNum;
    private javax.swing.JTextField txtStatusField;
    // End of variables declaration//GEN-END:variables
}
