/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.sun.org.apache.bcel.internal.generic.IF_ACMPEQ;
import model.Product;

/**
 * @author Lynn Wei
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel_1
     */
    Product product;

    public CreateJPanel(Product product) {
        this.product=product;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblNuid_num = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeo_data = new javax.swing.JTextField();
        txtNuid_num = new javax.swing.JTextField();
        txtEmail_add = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtTele_num = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblGeo_data = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTele_num = new javax.swing.JLabel();
        txtFax_num = new javax.swing.JTextField();
        lblEmail_add = new javax.swing.JLabel();
        lalFax_num = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        lblLinkedln = new javax.swing.JLabel();
        lblDevice_iden = new javax.swing.JLabel();
        lblMedi_num = new javax.swing.JLabel();
        lblHealth_num = new javax.swing.JLabel();
        lblInter_add = new javax.swing.JLabel();
        lblVehicle_iden = new javax.swing.JLabel();
        lblBank_num = new javax.swing.JLabel();
        txtMedi_num = new javax.swing.JTextField();
        txtHealth_num = new javax.swing.JTextField();
        txtBank_num = new javax.swing.JTextField();
        txtLinkedln = new javax.swing.JTextField();
        txtCerti_num = new javax.swing.JTextField();
        txtVehicle_iden = new javax.swing.JTextField();
        txtDevice_iden = new javax.swing.JTextField();
        txtInter_add = new javax.swing.JTextField();
        lblCerti_num = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Eras Medium ITC", 1, 48)); // NOI18N
        lblTitle.setText("Create Personal Profile");

        lblNuid_num.setText("NUID number:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtNuid_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuid_numActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        lblGeo_data.setText("Geographic data:");

        lblDob.setText("DOB(MM/DD/YYYY):");

        lblTele_num.setText("Telephone numbers:");

        lblEmail_add.setText("Email address:");

        lalFax_num.setText("FAX number:");

        lblSsn.setText("SSN:");

        txtSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsnActionPerformed(evt);
            }
        });

        lblLinkedln.setText("Linkedln:");

        lblDevice_iden.setText("Device identifiers:");

        lblMedi_num.setText("Medical record numbers:");

        lblHealth_num.setText("Health plan beneficiary number:");

        lblInter_add.setText("Internet protocol addresses：");

        lblVehicle_iden.setText("Vehicle identifiers:");

        lblBank_num.setText("Bank account numbers:");

        txtLinkedln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedlnActionPerformed(evt);
            }
        });

        txtInter_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInter_addActionPerformed(evt);
            }
        });

        lblCerti_num.setText("Certificate/License number:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload photo");

        //*
        // 点击该按钮，打开上传图片窗口，因为点击右上角关闭会直接关闭系统，增加了关闭当前页面的按钮
        // *
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPho frame = new UploadPho();
                frame.setVisible(true);

                //关闭当前窗口
                JButton close = new JButton("关闭");
                close.setBounds(300, 264, 141, 46);
                close.setFont(new Font("宋体", Font.BOLD, 18));
                frame.add(close);
                close.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        frame.setVisible(false);
                    }
                });
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(8, 8, 8))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGap(54, 54, 54)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblEmail_add, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblGeo_data, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblNuid_num, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblDob)
                                                                        .addComponent(lblTele_num)
                                                                        .addComponent(lalFax_num, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(txtFax_num, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtTele_num, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtEmail_add, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtNuid_num, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtGeo_data, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblLinkedln, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblVehicle_iden)
                                                                        .addComponent(lblBank_num, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblCerti_num, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblDevice_iden, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblInter_add)
                                                                        .addComponent(lblHealth_num)
                                                                        .addComponent(lblMedi_num, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(txtLinkedln, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtInter_add, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtMedi_num, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtHealth_num, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtBank_num, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtCerti_num, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtDevice_iden, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtVehicle_iden, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(172, 172, 172))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(351, 351, 351)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtEmail_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblEmail_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(21, 21, 21)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(lblGeo_data, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtGeo_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtNuid_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblNuid_num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblTele_num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtTele_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtFax_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lalFax_num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(61, 61, 61)
                                                                .addComponent(txtHealth_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txtMedi_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblMedi_num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblHealth_num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(lblLinkedln, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtLinkedln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblBank_num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtBank_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblCerti_num, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtCerti_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblVehicle_iden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtVehicle_iden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblDevice_iden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtDevice_iden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblInter_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtInter_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(74, 74, 74))
        );
    }// </editor-fold>//GEN-END:initComponents

    /*
     * 保存的方法
     * */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        //填写内容的非空校验,为空有两种情况，一种是null，一种是空字符串''
        if (txtName.getText() == null || txtName.getText().isEmpty()
                || txtNuid_num.getText() == null || txtNuid_num.getText().isEmpty()
                || txtGeo_data.getText() == null || txtGeo_data.getText().isEmpty()
                || txtDob.getText() == null || txtDob.getText().isEmpty()
                || txtTele_num.getText() == null || txtTele_num.getText().isEmpty()
                || txtFax_num.getText() == null || txtFax_num.getText().isEmpty()
                || txtEmail_add.getText() == null || txtEmail_add.getText().isEmpty()
                || txtSsn.getText() == null || txtSsn.getText().isEmpty()
                || txtMedi_num.getText() == null || txtMedi_num.getText().isEmpty()
                || txtHealth_num.getText() == null || txtHealth_num.getText().isEmpty()
                || txtBank_num.getText() == null || txtBank_num.getText().isEmpty()
                || txtCerti_num.getText() == null || txtCerti_num.getText().isEmpty()
                || txtVehicle_iden.getText() == null || txtVehicle_iden.getText().isEmpty()
                || txtDevice_iden.getText() == null || txtDevice_iden.getText().isEmpty()
                || txtLinkedln.getText() == null || txtLinkedln.getText().isEmpty()
                || txtInter_add.getText() == null || txtInter_add.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sorry, the text box cannot be empty.");
            return;
        }

        //全局校验标识，默认是成功，后续如果有存在一个校验不合规则设置为失败，根据这个表示返回错误
        boolean validFlag = true;
        String validStr="";
        boolean isMatch;

        //Linkedln：^http://([\w-]+.)+[\w-]+(/[\w-./?%&=]*)?
        isMatch = Pattern.matches("(?:https://www.linkedin.com/[a-zA-Z0-9_-]).*", txtLinkedln.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[Linkedln] ";
        }


        //判断Nuid是否为9位数字
        isMatch = Pattern.matches("\\d{9}", txtNuid_num.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[Nuid] ";
        }

        //Telephon：判断是否为10位数字
        isMatch = Pattern.matches("\\d{10}", txtTele_num.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[Telephon] ";
        }

        //FAX:判断是否为10位数字
        isMatch = Pattern.matches("\\d{10}", txtFax_num.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[FAX] ";
        }

        //SSN：判断是否为9位数字
        isMatch = Pattern.matches("\\d{9}", txtSsn.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[SSN] ";
        }

        //Medical record number：判断是否为7位数字
        isMatch = Pattern.matches("\\d{7}", txtMedi_num.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[Medical_record_number] ";
        }

        //Health plan beneficiary number：判断是否为7位数字
        isMatch = Pattern.matches("\\d{7}", txtHealth_num.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[Health_plan_beneficiary_number] ";
        }

        //Bank account number：判断数字个数在10-20之间
        isMatch = Pattern.matches("\\d{10,20}", txtBank_num.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[Bank_account_number] ";
        }

        //Certi_num：判断数字7位！
        isMatch = Pattern.matches("\\d{7}", txtCerti_num.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[Certi_num] ";
        }

        //Email地址：^\w+[-+.]\w+)@\w+([-.]\w+).\w+([-.]\w+)*$
        isMatch = Pattern.matches("^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\\.[a-zA-Z0-9_-]+)+$", txtEmail_add.getText());
        if (!isMatch){
            validFlag=false;
            validStr+="[Email] ";
        }


        //通过JAVA自带的日期格式转换工具转换，转换成功则日期格式合法，不成功则非法，Dob：MM/DD/YYYY
        DateFormat df=new SimpleDateFormat("MM/DD/YYYY");
        try {
            df.parse(txtDob.getText());
        }catch (Exception e){
            validFlag=false;
            validStr+="[Dob] ";
        }


        if (!validFlag){
            JOptionPane.showMessageDialog(this, "Sorry, please enter a valid value."+validStr);
            return;
        }


        product.setName(txtName.getText());
        product.setGeo_data(txtGeo_data.getText());
        product.setVehicle_iden(txtVehicle_iden.getText());
        product.setDevice_iden(txtDevice_iden.getText());
        product.setInter_add(txtInter_add.getText());

        product.setNuid_num(txtNuid_num.getText());
        product.setTele_num(txtTele_num.getText());
        product.setFax_num(txtFax_num.getText());
        product.setSsn(txtSsn.getText());
        product.setMedi_num(txtMedi_num.getText());
        product.setHealth_num(txtHealth_num.getText());
        product.setBank_num(txtBank_num.getText());
        product.setCerti_num(txtCerti_num.getText());

        product.setEmail_add(txtEmail_add.getText());
        product.setLinkedln(txtLinkedln.getText());

        product.setDob(txtDob.getText());

        JOptionPane.showMessageDialog(this, "Personal Profile Information Saved.");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtInter_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInter_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInter_addActionPerformed

    private void txtSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsnActionPerformed

    private void txtLinkedlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedlnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedlnActionPerformed

    private void txtNuid_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuid_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuid_numActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel lalFax_num;
    private javax.swing.JLabel lblBank_num;
    private javax.swing.JLabel lblCerti_num;
    private javax.swing.JLabel lblDevice_iden;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail_add;
    private javax.swing.JLabel lblGeo_data;
    private javax.swing.JLabel lblHealth_num;
    private javax.swing.JLabel lblInter_add;
    private javax.swing.JLabel lblLinkedln;
    private javax.swing.JLabel lblMedi_num;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNuid_num;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTele_num;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicle_iden;
    private javax.swing.JTextField txtBank_num;
    private javax.swing.JTextField txtCerti_num;
    private javax.swing.JTextField txtDevice_iden;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail_add;
    private javax.swing.JTextField txtFax_num;
    private javax.swing.JTextField txtGeo_data;
    private javax.swing.JTextField txtHealth_num;
    private javax.swing.JTextField txtInter_add;
    private javax.swing.JTextField txtLinkedln;
    private javax.swing.JTextField txtMedi_num;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNuid_num;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTele_num;
    private javax.swing.JTextField txtVehicle_iden;
    // End of variables declaration//GEN-END:variables
}
