/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.captain;

import api.TravelSystem;
import api.employee.Employee;
import api.organization.*;
import api.property.*;
import api.property.Airplane;
import api.request.Entering;
import api.request.Flight;
import api.request.request;
import api.request.Landing;
import api.userAccount.UserAccount;
import api.request.TrainLine;
import api.request.TrainTicket;
import ui.Airport.*;
import ui.AirlineCompany.*;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author wangqingtang
 */
public class TraCapPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlineCompanyJPanel
     */
    JPanel container;
    private TravelSystem system;
    private Employee account;
    private RailwayCompany railwayCompany;
    public TraCapPanel(JPanel container,Employee em,TravelSystem system, Organization o) {
        this.system = system;
        this.account = em;
        this.railwayCompany = (RailwayCompany) o;
        this.container = container;
        initComponents();
        populateTable();
    }
    
    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        int size = model.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
        List<request> requests = railwayCompany.getRequestDirectory().getRequestList();
        SimpleDateFormat sdf = new SimpleDateFormat("MM-dd hh:mm");
        for (request request : requests) {
            TrainLine trainLine = (TrainLine)request;
            if(trainLine.getCaptain().getName().equals(account.getName())){
            Object[] row = new Object[6];
            row[0] = trainLine;
            row[1] = trainLine.getId();
            row[2] = trainLine.getCurrentStation();
            row[3] = trainLine.getNextStation();
            row[4] = trainLine.getStartDate() == null ? "" : sdf.format( trainLine.getStartDate());
            row[5] = trainLine.getEndDate() == null ? "" : sdf.format( trainLine.getEndDate());
            model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle.setText("Train Captain");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 15, -1, -1));

        workRequestJTable.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Id", "CurrentStation", "NextStation", "StartDate", "EndDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(30);
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setMinWidth(0);
            workRequestJTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            workRequestJTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 820, 280));

        jButton4.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton4.setText("Entering Request");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 220, 42));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/captain/Backbutton_3.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 22, 60, 60));

        jButton5.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton5.setText("Entering Finish");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 200, 42));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/captain/traincap_1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, -20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        /*LandingPanel editflightInfoPanel = new LandingPanel(container);
        container.add("LandingPanel", editflightInfoPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);*/
        int row = workRequestJTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            JOptionPane.showMessageDialog(null, " Request send success!!", "Success", JOptionPane.WARNING_MESSAGE);
        }
        TrainLine trainLine = (TrainLine) workRequestJTable.getValueAt(row, 0);
        String type = "";
        String status = "";
        Entering entering = new Entering(type, status, trainLine);
        system.getOrganizationByNameAndType("Station", trainLine.getNextStation()).
                getRequestDirectory().
                addRequest(entering);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         int row = workRequestJTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        TrainLine trainLine = (TrainLine) workRequestJTable.getValueAt(row, 0);
        List<request> requestList = system.getOrganizationByNameAndType("Station", trainLine.getNextStation()).
                getRequestDirectory()
                .getRequestList();
        for (request req: requestList){
            if (!(req instanceof Entering)){
                continue;
            }
            Entering entering = (Entering) req;
            if (entering.getTrainLine() == trainLine){
                if(!trainLine.moveNextStation()){
                    JOptionPane.showMessageDialog(null, "This is the last station.", "Finished", JOptionPane.WARNING_MESSAGE);
                    trainLine.setStatus("Finished");
                    requestList = system.getOrganizationByIdAndType("RailwayCompany", trainLine.getOrganizationId()).
                        getRequestDirectory()
                        .getRequestList();
                    if(trainLine.getType().equals("Normal")){
                        for (request req1: requestList){
                            if (!(req1 instanceof TrainTicket)){
                            continue;
                            }
                            TrainTicket trainTicket = (TrainTicket) req;
                            if (trainTicket.getTrainLineId() == trainLine.getId()){
                                trainTicket.setStatus("Finished");
                            }
                        }
                    }
                }
                entering.Finish();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
