/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DeliveryManRole;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import business.DB4OUtil.OrderDBUtil;
import business.dto.OrderDto;
import business.dto.UserDto;

/**
 *
 * @author raunak
 */
public class DeliveryManWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserDto userDto;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public DeliveryManWorkAreaJPanel(JPanel userProcessContainer, UserDto userDto) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userDto = userDto;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        List<OrderDto> orderList = OrderDBUtil.queryByDelName(this.userDto.getUserName());
        for (int i = 0; i < orderList.size(); i++) {
            Object[] data = new Object[5];
            data[0] = orderList.get(i).getRestaurantName();
            data[1] = orderList.get(i).getMeal();
            data[2] = orderList.get(i).getUserName();
            data[3] = orderList.get(i).getStatus();
            data[4] = orderList.get(i).getId();
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processJButton.setText("Finish");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 130, 40));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Restaurant", "Meal", "Customer UserName", "Status", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, 
                java.lang.String.class, 
                java.lang.String.class, 
                java.lang.String.class,
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(30);
        TableColumn tc = workRequestJTable.getTableHeader().getColumnModel().getColumn(4);
        tc.setMaxWidth(0);
        tc.setWidth(0);
        tc.setMinWidth(0);
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 690, 280));

        lblTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lblTitle.setText("Manage Delivery");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        int i = workRequestJTable.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a line.");
            return;
        }
        String status = (String)workRequestJTable.getModel().getValueAt(i, 3);
        if (!status.equals("Pending")) {
            return;
        }
        String id = (String)workRequestJTable.getModel().getValueAt(i, 4);
        OrderDto orderDto = OrderDBUtil.queryById(id);
        orderDto.setStatus("Finished");
        OrderDBUtil.update(orderDto);
        workRequestJTable.getModel().setValueAt("Finished", i, 3);
        JOptionPane.showMessageDialog(null, "Finshed.");
    }//GEN-LAST:event_processJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton processJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
