/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RailwayCompany;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import api.BoxHelper;
import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.enterprise.Enterprise;
import api.organization.AirlineCompany;
import api.organization.Airport;
import api.organization.Organization;
import api.organization.RailwayCompany;
import api.organization.Station;
import api.property.Airplane;
import api.property.Train;
import api.request.Flight;
import api.request.TrainLine;
import api.request.request;

/**
 *
 * @author Lynn Wei
 */
public class AddRouteJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private BoxHelper<Train>[] trains = new BoxHelper[0];
    private BoxHelper<Station>[] stations = new BoxHelper[0];
    private BoxHelper<Employee>[] trainCaptains = new BoxHelper[0];
    
    public AddRouteJPanel(JPanel userProcessContainer, Employee employee, TravelSystem system, Organization origanization) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<Train> trainList = railwayCompany.getTrainList();
        trains = new BoxHelper[trainList.size()];
        for (int i = 0; i < trains.length; i++) {
            trains[i] = new BoxHelper<>(trainList.get(i).getId(), trainList.get(i));
        }
        
        getStageList();
        getEmployeeList();
        initComponents();
        cmbTrainId.setSelectedItem(null);
        cmbLandStation.setSelectedItem(null);
        cmbDeStation.setSelectedItem(null);
        cmbConductor.setSelectedItem(null);
    }

    private void getStageList() {
        ArrayList<Enterprise> enterpriseList = system.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise enterprise : enterpriseList) {
            if (enterprise.getName().equals("Station")) {
                List<Organization> orgList = enterprise.getOrganizationDirectory().getOrganizationList();
                stations = new BoxHelper[orgList.size()];
                for (int i = 0; i < orgList.size(); i++) {
                    Station station = (Station)orgList.get(i);
                    stations[i] = new BoxHelper<>(station.getId(), station);
                }
            }
        }
    }
    
    private void getEmployeeList() {
        RailwayCompany railway = (RailwayCompany)origanization;
        List<Employee> employeeList = new ArrayList<>();
        for (Employee employee : railway.getEmployeeDirectory().getEmployeeList()) {
            if (employee.getRole().getRole().equals("TrainCaptain")) {
                employeeList.add(employee);
            }
        }
        trainCaptains = new BoxHelper[employeeList.size()];
        for (int i = 0; i < employeeList.size(); i++) {
            trainCaptains[i] = new BoxHelper<>(employeeList.get(i).getName(), employeeList.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTitle8 = new javax.swing.JLabel();
        txtDeDate = new javax.swing.JTextField();
        lblTitle6 = new javax.swing.JLabel();
        lblTitle7 = new javax.swing.JLabel();
        lblTitle13 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        txtSecondNum = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        txtBusi = new javax.swing.JLabel();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle16 = new javax.swing.JLabel();
        cmbTrainId = new javax.swing.JComboBox<>();
        cmbDeStation = new javax.swing.JComboBox<>();
        cmbLandStation = new javax.swing.JComboBox<>();
        cmbConductor = new javax.swing.JComboBox<>();
        txtRouteNum = new javax.swing.JTextField();
        lblTitle4 = new javax.swing.JLabel();
        txtRouteType = new javax.swing.JTextField();
        lblTitle15 = new javax.swing.JLabel();
        lblTitle17 = new javax.swing.JLabel();
        txtSecondPrice = new javax.swing.JTextField();
        txtFirstNum = new javax.swing.JTextField();
        txtFirstPrice = new javax.swing.JTextField();
        lblTitle18 = new javax.swing.JLabel();
        lblTitle19 = new javax.swing.JLabel();
        txtSleeperNum = new javax.swing.JTextField();
        txtSleepPrice = new javax.swing.JTextField();
        lblTitle20 = new javax.swing.JLabel();
        lblTitle21 = new javax.swing.JLabel();
        lblTitle22 = new javax.swing.JLabel();
        lblTitle23 = new javax.swing.JLabel();
        txtFirstSleepNum = new javax.swing.JTextField();
        txtFirstSleepPrice = new javax.swing.JTextField();
        lblTitle24 = new javax.swing.JLabel();
        cmbIntermediateStation = new javax.swing.JComboBox<>();
        lblIntermediateStation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtStatusField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 149, 42));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 50));

        lblTitle8.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblTitle8.setText("Add Route");
        add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        txtDeDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtDeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 123, 167, 30));

        lblTitle6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle6.setText("Departure station:");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 257, -1, -1));

        lblTitle7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle7.setText("Landing station:");
        add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 347, -1, -1));

        lblTitle13.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle13.setText("Sleeper class:");
        add(lblTitle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        lblTitle3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        add(lblTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(989, 165, -1, -1));

        txtSecondNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtSecondNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 168, 83, 30));

        lblTitle.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle.setText("Route number:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 123, -1, -1));

        lblTitle5.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle5.setText("Depature date:");
        add(lblTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle1.setText("Train number/ID:");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 212, -1, -1));

        txtBusi.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtBusi.setText("First class:");
        add(txtBusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 212, -1, -1));

        lblTitle14.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle14.setText("Price:");
        add(lblTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 168, -1, -1));

        lblTitle16.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle16.setText("Conductor:");
        add(lblTitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 389, -1, -1));

        cmbTrainId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbTrainId.setModel(new DefaultComboBoxModel<>(trains));
        cmbTrainId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTrainIdItemStateChanged(evt);
            }
        });
        add(cmbTrainId, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 212, 145, 30));

        cmbDeStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbDeStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbDeStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeStationActionPerformed(evt);
            }
        });
        add(cmbDeStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 257, 145, 30));

        cmbLandStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbLandStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        add(cmbLandStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 347, 145, 30));

        cmbConductor.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbConductor.setModel(new DefaultComboBoxModel<>(trainCaptains));
        cmbConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConductorActionPerformed(evt);
            }
        });
        add(cmbConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 389, 145, 30));

        txtRouteNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtRouteNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 123, 144, 30));

        lblTitle4.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle4.setText("Route Type:");
        add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 168, -1, -1));

        txtRouteType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtRouteType.setText("Normal");
        add(txtRouteType, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 168, 144, 30));

        lblTitle15.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle15.setText("Second class: ");
        add(lblTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        lblTitle17.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle17.setText("Number:");
        add(lblTitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 168, -1, -1));

        txtSecondPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtSecondPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 168, 83, 30));

        txtFirstNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNumActionPerformed(evt);
            }
        });
        add(txtFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 212, 83, 30));

        txtFirstPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtFirstPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 212, 83, 30));

        lblTitle18.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle18.setText("Price:");
        add(lblTitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 212, -1, -1));

        lblTitle19.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle19.setText("Number:");
        add(lblTitle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 212, -1, -1));

        txtSleeperNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtSleeperNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 257, 83, 30));

        txtSleepPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtSleepPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 257, 83, 30));

        lblTitle20.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle20.setText("Price:");
        add(lblTitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 257, -1, -1));

        lblTitle21.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle21.setText("Number:");
        add(lblTitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 257, -1, -1));

        lblTitle22.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle22.setText("Number:");
        add(lblTitle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 302, -1, -1));

        lblTitle23.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle23.setText("First Sleeper class:");
        add(lblTitle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        txtFirstSleepNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtFirstSleepNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 302, 83, 30));

        txtFirstSleepPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtFirstSleepPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 302, 83, 30));

        lblTitle24.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle24.setText("Price:");
        add(lblTitle24, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 302, -1, -1));

        cmbIntermediateStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbIntermediateStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Danville", "Boston", "NewYork" }));
        add(cmbIntermediateStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 302, 145, 30));

        lblIntermediateStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblIntermediateStation.setText("Intermediate station:");
        add(lblIntermediateStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 302, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel1.setText("Status:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 347, -1, -1));

        txtStatusField.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtStatusField.setText("Not Started");
        add(txtStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 120, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/train1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 600, 380));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/earth_1.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String id = txtRouteNum.getText();
        String type = txtRouteType.getText();
        BoxHelper<Train> train = (BoxHelper<Train>)cmbTrainId.getSelectedItem();
        String deStation = (String)cmbDeStation.getSelectedItem();
        String inStation = (String)cmbIntermediateStation.getSelectedItem();
        String laStation = (String)cmbLandStation.getSelectedItem();
        BoxHelper<Employee> conductor = (BoxHelper<Employee>)cmbConductor.getSelectedItem();
        String status = txtStatusField.getText();
        Date sDate;
        SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
        try {
            sDate = sdf.parse(txtDeDate.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Depature Date format error!");
            return;
        }
        int rSS = Integer.parseInt(txtSecondNum.getText());
        int rFSS = Integer.parseInt(txtFirstNum.getText());
        int rS = Integer.parseInt(txtSleeperNum.getText());
        int rFS = Integer.parseInt(txtFirstSleepNum.getText());
        double sSP = Double.parseDouble(txtSecondPrice.getText());
        double fSSP = Double.parseDouble(txtFirstPrice.getText());
        double sP = Double.parseDouble(txtSleepPrice.getText());
        double fSP = Double.parseDouble(txtFirstSleepPrice.getText());
        
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<request> requests = railwayCompany.getRequestDirectory().getRequestList();
        for (request request : requests) {
            if (request instanceof TrainLine) {
                TrainLine trainLine = (TrainLine)request;
                if (trainLine.getId() == Integer.parseInt(id)) {
                    JOptionPane.showMessageDialog(null, "Route number already exists!");
                    return;
                }
                if (trainLine.getStartDate() != null && 
                    trainLine.getCaptain() != null &&
                    sdf.format(sDate).substring(0, 5).equals(sdf.format(trainLine.getStartDate()).substring(0, 5))
                    && conductor.getData().getId() == trainLine.getCaptain().getId()) {
                    JOptionPane.showMessageDialog(null, "The same person can only arrange one shift a day!");
                    return;
                }
              
            }
        }
        
        if (deStation.equals(inStation) || laStation.equals(inStation) || deStation.equals(laStation)) {
            JOptionPane.showMessageDialog(null, "Train station repeat!");
            return;
        }
         if (txtRouteNum.getText() == null || txtRouteNum.getText().isEmpty()
                || txtDeDate.getText() == null || txtDeDate.getText().isEmpty()
                || txtSecondPrice.getText() == null || txtSecondPrice.getText().isEmpty()
                || txtFirstPrice.getText() == null || txtFirstPrice.getText().isEmpty()
                || txtSleepPrice.getText() == null || txtSleepPrice.getText().isEmpty()
                || txtFirstSleepPrice.getText() == null || txtFirstSleepPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sorry, the text box cannot be empty.");
            return;
        } 
        
        TrainLine trainLine = new TrainLine(employee.getId()+"", origanization.getId(), type, status, sDate, null, Integer.parseInt(id));
        ArrayList<String> sL = new ArrayList<>();
        sL.add(deStation);
        sL.add(inStation);
        sL.add(laStation);
        trainLine.setTrainLine(sL, 0, conductor.getData(), train.getData(), rSS, rFSS, rS, rFS, sSP, fSSP, sP, fSP);
        requests.add(trainLine);
        DB4OUtil.getInstance().storeSystem(system);
        // Information Added Succesfully!
        JOptionPane.showMessageDialog(null, "Information Added Succesfully!");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ShowRouteJPanel rwajp = new ShowRouteJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("ShowRouteJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbTrainIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTrainIdItemStateChanged
        // TODO add your handling code here:
        BoxHelper<Train> helper = (BoxHelper<Train>)cmbTrainId.getSelectedItem();
        if (null == helper) {
            return;
        }
        Train train = helper.getData();
        txtSecondNum.setText("" + train.getSecondSeatNumber());
        txtFirstNum.setText("" + train.getFirstSeatNumber());
        txtSleeperNum.setText("" + train.getSleeperNumber());
        txtFirstSleepNum.setText("" + train.getFirstSleeperNumber());
    }//GEN-LAST:event_cmbTrainIdItemStateChanged

    private void cmbDeStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDeStationActionPerformed

    private void cmbConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConductorActionPerformed

    private void txtFirstNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<BoxHelper<Employee>> cmbConductor;
    private javax.swing.JComboBox<String> cmbDeStation;
    private javax.swing.JComboBox<String> cmbIntermediateStation;
    private javax.swing.JComboBox<String> cmbLandStation;
    private javax.swing.JComboBox<BoxHelper<Train>> cmbTrainId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIntermediateStation;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle13;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle16;
    private javax.swing.JLabel lblTitle17;
    private javax.swing.JLabel lblTitle18;
    private javax.swing.JLabel lblTitle19;
    private javax.swing.JLabel lblTitle20;
    private javax.swing.JLabel lblTitle21;
    private javax.swing.JLabel lblTitle22;
    private javax.swing.JLabel lblTitle23;
    private javax.swing.JLabel lblTitle24;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel txtBusi;
    private javax.swing.JTextField txtDeDate;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtFirstPrice;
    private javax.swing.JTextField txtFirstSleepNum;
    private javax.swing.JTextField txtFirstSleepPrice;
    private javax.swing.JTextField txtRouteNum;
    private javax.swing.JTextField txtRouteType;
    private javax.swing.JTextField txtSecondNum;
    private javax.swing.JTextField txtSecondPrice;
    private javax.swing.JTextField txtSleepPrice;
    private javax.swing.JTextField txtSleeperNum;
    private javax.swing.JTextField txtStatusField;
    // End of variables declaration//GEN-END:variables
}
