/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RailwayCompany;

import java.awt.CardLayout;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.organization.Organization;
import api.organization.RailwayCompany;
import api.property.Train;

/**
 *
 * @author Lynn Wei
 */
public class AddTrainJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    
    public AddTrainJPanel(JPanel userProcessContainer, Employee employee, TravelSystem system, Organization origanization) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTrainType = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtTrainId = new javax.swing.JTextField();
        lblTitle6 = new javax.swing.JLabel();
        lblTitle7 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblTitle8 = new javax.swing.JLabel();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle15 = new javax.swing.JLabel();
        txtSeatNumber = new javax.swing.JTextField();
        txtSecondNum = new javax.swing.JTextField();
        txtFirstNum = new javax.swing.JTextField();
        lblTitle20 = new javax.swing.JLabel();
        lblTitle9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblTitle16 = new javax.swing.JLabel();
        txtSleepNum = new javax.swing.JTextField();
        txtFirstSleepNum = new javax.swing.JTextField();
        lblTitle21 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTrainType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtTrainType, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 167, 30));

        lblTitle.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle.setText("Train type:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        btnAdd.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 149, 42));

        txtTrainId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtTrainId, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 167, 30));

        lblTitle6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle6.setText("Train number/ID:");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        lblTitle7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle7.setText("Year:");
        add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        txtYear.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 167, 30));

        lblTitle8.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblTitle8.setText("Add Train");
        add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 60));

        lblTitle14.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle14.setText("Second class seats number:");
        add(lblTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        lblTitle15.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle15.setText("Seats number:");
        add(lblTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        txtSeatNumber.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtSeatNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 167, 30));

        txtSecondNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtSecondNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 100, 30));

        txtFirstNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 100, 30));

        lblTitle20.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle20.setText("First class seats number:");
        add(lblTitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        lblTitle9.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle9.setText("Age:");
        add(lblTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        txtAge.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 167, 30));

        lblTitle16.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle16.setText("Sleeper number:");
        add(lblTitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        txtSleepNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtSleepNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 100, 30));

        txtFirstSleepNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(txtFirstSleepNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 100, 30));

        lblTitle21.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle21.setText("First sleeper number:");
        add(lblTitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/AirlineCompany/earth_1.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/train5.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 470, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String id = txtTrainId.getText();
        String type = txtTrainType.getText();
        int year = Integer.parseInt(txtYear.getText());
        int age = Integer.parseInt(txtAge.getText());
        int seatNumber = Integer.parseInt(txtSeatNumber.getText());
        int secondSeatNumber = Integer.parseInt(txtSecondNum.getText());
        int firstSeatNumber = Integer.parseInt(txtFirstNum.getText());
        int sleeperNumber = Integer.parseInt(txtSleepNum.getText());
        int firstSleeperNumber = Integer.parseInt(txtFirstSleepNum.getText());
        
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<Train> trainList = railwayCompany.getTrainList();
        for (Train train : trainList) {
            if (train.getId().equals(id)) {
                JOptionPane.showMessageDialog(null, "Train number/ID already exists!");
                return;
            }
        }
        Train train = new Train(id, type, year, age, seatNumber, 
            secondSeatNumber, firstSeatNumber, sleeperNumber, firstSleeperNumber, 1);
        railwayCompany.addTrain(train);
        DB4OUtil.getInstance().storeSystem(system);
        // Information Added Succesfully!
        JOptionPane.showMessageDialog(null, "Information Added Succesfully!");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ShowTrainJPanel rwajp = new ShowTrainJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("ShowTrainJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle16;
    private javax.swing.JLabel lblTitle20;
    private javax.swing.JLabel lblTitle21;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtFirstSleepNum;
    private javax.swing.JTextField txtSeatNumber;
    private javax.swing.JTextField txtSecondNum;
    private javax.swing.JTextField txtSleepNum;
    private javax.swing.JTextField txtTrainId;
    private javax.swing.JTextField txtTrainType;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
