/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RailwayCompany;

import java.awt.CardLayout;

import javax.swing.JPanel;

import api.TravelSystem;
import api.employee.Employee;
import api.organization.Organization;
import api.userAccount.UserAccount;

/**
 *
 * @author 10857
 */
public class RailwayCompanyPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    
    public RailwayCompanyPanel(JPanel userProcessContainer, Employee employee, TravelSystem system, Organization origanization) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFlight = new javax.swing.JButton();
        btnPlane = new javax.swing.JButton();
        lblCompany = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFlight.setFont(new java.awt.Font("Gabriola", 1, 30)); // NOI18N
        btnFlight.setText("Manage Trainline");
        btnFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightActionPerformed(evt);
            }
        });
        add(btnFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 471, 54));

        btnPlane.setFont(new java.awt.Font("Gabriola", 1, 30)); // NOI18N
        btnPlane.setText("Manage Train");
        btnPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaneActionPerformed(evt);
            }
        });
        add(btnPlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 471, 54));

        lblCompany.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblCompany.setText(origanization.getName());
        add(lblCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 534, -1));

        lblTitle.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle.setText("Welcome to Railway Company:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/train4.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 780, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightActionPerformed
        // TODO add your handling code here:
        ShowRouteJPanel showPlaneJPanel = new ShowRouteJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("ShowRouteJPanel", showPlaneJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFlightActionPerformed

    private void btnPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaneActionPerformed
        // TODO add your handling code here:
        ShowTrainJPanel showPlaneJPanel = new ShowTrainJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("ShowTrainJPanel", showPlaneJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPlaneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlight;
    private javax.swing.JButton btnPlane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
