/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RailwayCompany;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.organization.Organization;
import api.organization.RailwayCompany;
import api.request.TrainLine;
import api.request.request;

/**
 *
 * @author Lynn Wei
 */
public class ShowRouteJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private List<request> trainlineList = new ArrayList<>();
    
    public ShowRouteJPanel(JPanel userProcessContainer, Employee employee, TravelSystem system, Organization origanization) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        initComponents();
        initTrainline();
        populateRequestTable();
    }
    
    private void initTrainline() {
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<request> requests = railwayCompany.getRequestDirectory().getRequestList();
        for (request request : requests) {
            if (request instanceof TrainLine
                && !request.getStatus().equals("Unsolved")
                && !request.getStatus().equals("Canceled")) {
                trainlineList.add(request);
            }
        }
    }
    
    private void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int size = model.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
        for (request request : trainlineList) {
            TrainLine trainLine = (TrainLine)request;
            // "Route Number", "Departure Station", "Arriving Station", "Conductor", 
            // "Departure Date", "Route Type"
            Object[] row = new Object[7];
            row[0] = trainLine.getId();
            List<String> stationList = trainLine.getStationList();
            row[1] = null == stationList || stationList.isEmpty() ? "" : stationList.get(0);
            row[2] = null == stationList || stationList.size() < 2 ? "" : stationList.get(stationList.size() - 1);
            row[3] = trainLine.getCaptain() == null ? "" : trainLine.getCaptain().getName();
            SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
            row[4] = sdf.format(trainLine.getStartDate() == null ? new Date() : trainLine.getStartDate());
            row[5] = trainLine.getType();
            row[6] = trainLine.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N

        jTable1.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Route Number", "Departure Station", "Arriving Station", "Conductor", "Departure Date", "Route Type", "Status"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 765, 306));

        jButton1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton1.setText("Add Route");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 160, 30));

        jButton2.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton2.setText("View Route");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 168, 30));

        jButton3.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton3.setText("Delete Route");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 173, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 50));

        lblTitle1.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblTitle1.setText("Route Information");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/littletrain_1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/train9.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 360, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        UpdateRouteJPanel rwajp = new UpdateRouteJPanel(userProcessContainer, employee, system, 
            origanization, (TrainLine)trainlineList.get(i));
        userProcessContainer.add("UpdateRouteJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<request> requests = railwayCompany.getRequestDirectory().getRequestList();
        int id = Integer.parseInt(jTable1.getValueAt(i, 0).toString());
        for (request request : requests) {
            if (request instanceof TrainLine && request.getId() == id) {
                requests.remove(request);
                break;
            }
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        trainlineList.remove(i);
        model.removeRow(i);
        DB4OUtil.getInstance().storeSystem(system);
        JOptionPane.showMessageDialog(null, "Information Deleted Succesfully!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddRouteJPanel rwajp = new AddRouteJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("AddFlightJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        RailwayCompanyPanel showPlaneJPanel = new RailwayCompanyPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("RailwayCompanyPanel", showPlaneJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
