/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RailwayCompany;

import java.awt.CardLayout;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.organization.Organization;
import api.organization.RailwayCompany;
import api.property.Train;

/**
 *
 * @author Lynn Wei
 */
public class UpdateTrainJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private Train train;
    
    public UpdateTrainJPanel(JPanel userProcessContainer, Employee employee, 
        TravelSystem system, Organization origanization, Train train) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        this.train = train;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        lblTitle8 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle15 = new javax.swing.JLabel();
        txtTrainType = new javax.swing.JTextField();
        txtSeatNumber = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtSecondNum = new javax.swing.JTextField();
        txtTrainId = new javax.swing.JTextField();
        lblTitle6 = new javax.swing.JLabel();
        txtFirstNum = new javax.swing.JTextField();
        lblTitle7 = new javax.swing.JLabel();
        lblTitle20 = new javax.swing.JLabel();
        lblTitle9 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblTitle16 = new javax.swing.JLabel();
        txtSleepNum = new javax.swing.JTextField();
        txtFirstSleepNum = new javax.swing.JTextField();
        lblTitle21 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 149, 42));

        lblTitle8.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblTitle8.setText("Train Information");
        add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        txtAge.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtAge.setText(train.getAge()+"");
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 167, 30));

        lblTitle14.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle14.setText("Second class seats number:");
        add(lblTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        lblTitle15.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle15.setText("Seats number:");
        add(lblTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        txtTrainType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtTrainType.setText(train.getType());
        add(txtTrainType, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 167, 30));

        txtSeatNumber.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSeatNumber.setText(train.getSeatNumber()+"");
        txtSeatNumber.setToolTipText("");
        add(txtSeatNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 167, 30));

        lblTitle.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle.setText("Train type:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        txtSecondNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSecondNum.setText(train.getSecondSeatNumber()+"");
        add(txtSecondNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 100, 30));

        txtTrainId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtTrainId.setText(train.getId());
        add(txtTrainId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 167, 30));

        lblTitle6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle6.setText("Train number/ID:");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        txtFirstNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstNum.setText(train.getFirstSeatNumber()+"");
        add(txtFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 100, 30));

        lblTitle7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle7.setText("Year:");
        add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        lblTitle20.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle20.setText("First class seats number:");
        add(lblTitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        lblTitle9.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle9.setText("Age:");
        add(lblTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        txtYear.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtYear.setText(train.getYear()+"");
        add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 167, 30));

        lblTitle16.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle16.setText("Sleeper number:");
        add(lblTitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        txtSleepNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSleepNum.setText(train.getSleeperNumber()+"");
        add(txtSleepNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 100, 30));

        txtFirstSleepNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstSleepNum.setText(train.getFirstSleeperNumber()+"");
        add(txtFirstSleepNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 100, 30));

        lblTitle21.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle21.setText("First sleeper number:");
        add(lblTitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/train6.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 510, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/littletrain_1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = txtTrainId.getText();
        String type = txtTrainType.getText();
        int year = Integer.parseInt(txtYear.getText());
        int age = Integer.parseInt(txtAge.getText());
        int seatNumber = Integer.parseInt(txtSeatNumber.getText());
        int secondSeatNumber = Integer.parseInt(txtSecondNum.getText());
        int firstSeatNumber = Integer.parseInt(txtFirstNum.getText());
        int sleeperNumber = Integer.parseInt(txtSleepNum.getText());
        int firstSleeperNumber = Integer.parseInt(txtFirstSleepNum.getText());
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<Train> trainList = railwayCompany.getTrainList();
        for (Train train : trainList) {
            if (!this.train.getId().equals(train.getId()) && train.getId().equals(id)) {
                JOptionPane.showMessageDialog(null, "Train number/ID already exists!");
                return;
            }
        }
        train.setId(id);
        train.setType(type);
        train.setYear(year);
        train.setAge(age);
        train.setSeatNumber(seatNumber);
        train.setSecondSeatNumber(secondSeatNumber);
        train.setFirstSeatNumber(firstSeatNumber);
        train.setSleeperNumber(sleeperNumber);
        train.setFirstSleeperNumber(firstSleeperNumber);
        DB4OUtil.getInstance().storeSystem(system);
        JOptionPane.showMessageDialog(null, "Information Updated Succesfully!");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ShowTrainJPanel rwajp = new ShowTrainJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("ShowTrainJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle16;
    private javax.swing.JLabel lblTitle20;
    private javax.swing.JLabel lblTitle21;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtFirstSleepNum;
    private javax.swing.JTextField txtSeatNumber;
    private javax.swing.JTextField txtSecondNum;
    private javax.swing.JTextField txtSleepNum;
    private javax.swing.JTextField txtTrainId;
    private javax.swing.JTextField txtTrainType;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
