/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RailwayCompany;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import api.BoxHelper;
import api.TravelSystem;
import api.DB4oUtil.DB4OUtil;
import api.employee.Employee;
import api.enterprise.Enterprise;
import api.organization.Organization;
import api.organization.RailwayCompany;
import api.organization.Station;
import api.property.Train;
import api.request.TrainLine;
import api.request.request;

import javax.swing.DefaultComboBoxModel;
import ui.AirlineCompany.ShowFlightJPanel;

/**
 *
 * @author Lynn Wei
 */
public class UpdateRouteJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel userProcessContainer;
    private TravelSystem system;
    private Employee employee;
    private Organization origanization;
    private TrainLine trainLine;
    private BoxHelper<Train>[] trains = new BoxHelper[0];
    private BoxHelper<Station>[] stations = new BoxHelper[0];
    private BoxHelper<Employee>[] trainCaptains = new BoxHelper[0];
    private SimpleDateFormat sdf = new SimpleDateFormat("MM-dd HH:mm");
    
    public UpdateRouteJPanel(JPanel userProcessContainer, Employee employee, 
        TravelSystem system, Organization origanization, TrainLine trainLine) {
        this.system = system;
        this.employee = employee;
        this.origanization = origanization;
        this.userProcessContainer = userProcessContainer;
        this.trainLine = trainLine;
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<Train> trainList = railwayCompany.getTrainList();
        trains = new BoxHelper[trainList.size()];
        for (int i = 0; i < trains.length; i++) {
            trains[i] = new BoxHelper<>(trainList.get(i).getId(), trainList.get(i));
        }
        getStageList();
        getEmployeeList();
        initComponents();
    }
    
    private void getStageList() {
        ArrayList<Enterprise> enterpriseList = system.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise enterprise : enterpriseList) {
            if (enterprise.getName().equals("Station")) {
                List<Organization> orgList = enterprise.getOrganizationDirectory().getOrganizationList();
                stations = new BoxHelper[orgList.size()];
                for (int i = 0; i < orgList.size(); i++) {
                    Station station = (Station)orgList.get(i);
                    stations[i] = new BoxHelper<>(station.getId(), station);
                }
            }
        }
    }
    
    private void getEmployeeList() {
        RailwayCompany railway = (RailwayCompany)origanization;
        List<Employee> employeeList = new ArrayList<>();
        for (Employee employee : railway.getEmployeeDirectory().getEmployeeList()) {
            if (employee.getRole().getRole().equals("TrainCaptain")) {
                employeeList.add(employee);
            }
        }
        trainCaptains = new BoxHelper[employeeList.size()];
        for (int i = 0; i < employeeList.size(); i++) {
            trainCaptains[i] = new BoxHelper<>(employeeList.get(i).getName(), employeeList.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle8 = new javax.swing.JLabel();
        lblTitle21 = new javax.swing.JLabel();
        txtBusi = new javax.swing.JLabel();
        lblTitle14 = new javax.swing.JLabel();
        lblTitle16 = new javax.swing.JLabel();
        cmbTrainId = new javax.swing.JComboBox<>();
        cmbDeStation = new javax.swing.JComboBox<>();
        cmbLandStation = new javax.swing.JComboBox<>();
        cmbConductor = new javax.swing.JComboBox<>();
        txtRouteNum = new javax.swing.JTextField();
        lblTitle4 = new javax.swing.JLabel();
        txtRouteType = new javax.swing.JTextField();
        lblTitle22 = new javax.swing.JLabel();
        lblTitle15 = new javax.swing.JLabel();
        lblTitle17 = new javax.swing.JLabel();
        txtSecondPrice = new javax.swing.JTextField();
        txtDeDate = new javax.swing.JTextField();
        txtFirstNum = new javax.swing.JTextField();
        lblTitle23 = new javax.swing.JLabel();
        lblTitle6 = new javax.swing.JLabel();
        txtFirstPrice = new javax.swing.JTextField();
        txtFirstSleepNum = new javax.swing.JTextField();
        lblTitle7 = new javax.swing.JLabel();
        lblTitle18 = new javax.swing.JLabel();
        txtFirstSleepPrice = new javax.swing.JTextField();
        lblTitle13 = new javax.swing.JLabel();
        lblTitle19 = new javax.swing.JLabel();
        lblTitle24 = new javax.swing.JLabel();
        txtSleeperNum = new javax.swing.JTextField();
        txtSecondNum = new javax.swing.JTextField();
        txtSleepPrice = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblTitle20 = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblIntermediateStation = new javax.swing.JLabel();
        cmbIntermediateStation = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtStatusField = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle8.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        lblTitle8.setText("Route Information");
        add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        lblTitle21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTitle21.setText("Number:");
        add(lblTitle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, -1, -1));

        txtBusi.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtBusi.setText("First class:");
        add(txtBusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        lblTitle14.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle14.setText("Price:");
        add(lblTitle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, -1, -1));

        lblTitle16.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle16.setText("Conductor:");
        add(lblTitle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        cmbTrainId.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbTrainId.setModel(new DefaultComboBoxModel<>(trains));
        cmbTrainId.setSelectedItem(trainLine.getTrain() == null ? null : new BoxHelper<Train>(trainLine.getTrain().getId()+"", trainLine.getTrain()));
        cmbTrainId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTrainIdItemStateChanged(evt);
            }
        });
        add(cmbTrainId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 145, 30));

        cmbDeStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbDeStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbDeStation.setSelectedItem(trainLine.getStationList().get(0));
        add(cmbDeStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 145, 30));

        cmbLandStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbLandStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danville", "Boston", "NewYork" }));
        cmbLandStation.setSelectedItem(trainLine.getStationList().size() > 2 ? trainLine.getStationList().get(2) : trainLine.getStationList().get(1));
        add(cmbLandStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 145, 30));

        cmbConductor.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbConductor.setModel(new DefaultComboBoxModel<>(trainCaptains));
        cmbConductor.setSelectedItem(null == trainLine.getCaptain() ? null : new BoxHelper<Employee>(trainLine.getCaptain().getId()+"", trainLine.getCaptain()));
        cmbConductor.setToolTipText("");
        add(cmbConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 145, 30));

        txtRouteNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtRouteNum.setText(trainLine.getId()+"");
        add(txtRouteNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 144, 30));

        lblTitle4.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle4.setText("Route Type:");
        add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        txtRouteType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtRouteType.setText(trainLine.getType());
        add(txtRouteType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 144, 30));

        lblTitle22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTitle22.setText("Number:");
        add(lblTitle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, -1));

        lblTitle15.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle15.setText("Second class: ");
        add(lblTitle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        lblTitle17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTitle17.setText("Number:");
        add(lblTitle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, -1, -1));

        txtSecondPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSecondPrice.setText(trainLine.getSecondSeatPrice()+"");
        add(txtSecondPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 83, 30));

        txtDeDate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtDeDate.setText(sdf.format(trainLine.getStartDate()));
        add(txtDeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 167, 30));

        txtFirstNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstNum.setText(trainLine.getRemainFirstSeat()+"");
        add(txtFirstNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 83, 30));

        lblTitle23.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle23.setText("First Sleeper class:");
        add(lblTitle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        lblTitle6.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle6.setText("Departure station:");
        add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        txtFirstPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstPrice.setText(trainLine.getFirstSeatPrice()+"");
        add(txtFirstPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 83, 30));

        txtFirstSleepNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstSleepNum.setText(trainLine.getRemainFirstSleeper()+"");
        add(txtFirstSleepNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 83, 30));

        lblTitle7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle7.setText("Landing station:");
        add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        lblTitle18.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle18.setText("Price:");
        add(lblTitle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, -1, -1));

        txtFirstSleepPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtFirstSleepPrice.setText(trainLine.getFirstSleeperPrice()+"");
        add(txtFirstSleepPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, 83, 30));

        lblTitle13.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle13.setText("Sleeper class:");
        add(lblTitle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        lblTitle19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTitle19.setText("Number:");
        add(lblTitle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, -1, -1));

        lblTitle24.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle24.setText("Price:");
        add(lblTitle24, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, -1, -1));

        txtSleeperNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSleeperNum.setText(trainLine.getRemainSleeper()+"");
        add(txtSleeperNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 83, 30));

        txtSecondNum.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSecondNum.setText(trainLine.getRemainSecondSeat()+"");
        add(txtSecondNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 83, 30));

        txtSleepPrice.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtSleepPrice.setText(trainLine.getSleeperPrice()+"");
        txtSleepPrice.setToolTipText("");
        add(txtSleepPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, 83, 30));

        lblTitle.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle.setText("Route number:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        lblTitle20.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle20.setText("Price:");
        add(lblTitle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, -1, -1));

        lblTitle5.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle5.setText("Depature date:");
        add(lblTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblTitle1.setText("Train number/ID:");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        lblIntermediateStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblIntermediateStation.setText("Intermediate station:");
        add(lblIntermediateStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        cmbIntermediateStation.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cmbIntermediateStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Boston" }));
        cmbIntermediateStation.setSelectedItem(trainLine.getStationList().size() > 2 ? trainLine.getStationList().get(1) : "");
        cmbIntermediateStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIntermediateStationActionPerformed(evt);
            }
        });
        add(cmbIntermediateStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 145, 30));

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel1.setText("Status:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, -1));

        txtStatusField.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        txtStatusField.setText(trainLine.getStatus());
        add(txtStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 120, 40));

        btnUpdate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 121, 38));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/Backbutton_3.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/littletrain_1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 140, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/RailwayCompany/train7_1.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTrainIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTrainIdItemStateChanged
        // TODO add your handling code here:
         BoxHelper<Train> helper = (BoxHelper<Train>)cmbTrainId.getSelectedItem();
        if (null == helper) {
            return;
        }
        Train train = helper.getData();
        txtSecondNum.setText("" + train.getSecondSeatNumber());
        txtFirstNum.setText("" + train.getFirstSeatNumber());
        txtSleeperNum.setText("" + train.getSleeperNumber());
        txtFirstSleepNum.setText("" + train.getFirstSleeperNumber());
    }//GEN-LAST:event_cmbTrainIdItemStateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = txtRouteNum.getText();
        String type = txtRouteType.getText();
        BoxHelper<Train> train = (BoxHelper<Train>)cmbTrainId.getSelectedItem();
        String deStation = (String)cmbDeStation.getSelectedItem();
        String inStation = (String)cmbIntermediateStation.getSelectedItem();
        String laStation = (String)cmbLandStation.getSelectedItem();
        BoxHelper<Employee> conductor = (BoxHelper<Employee>)cmbConductor.getSelectedItem();
        String status = txtStatusField.getText();
        Date sDate;
        try {
            sDate = sdf.parse(txtDeDate.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Depature Date format error!");
            return;
        }
        int rSS = Integer.parseInt(txtSecondNum.getText());
        int rFSS = Integer.parseInt(txtFirstNum.getText());
        int rS = Integer.parseInt(txtSleeperNum.getText());
        int rFS = Integer.parseInt(txtFirstSleepNum.getText());
        double sSP = Double.parseDouble(txtSecondPrice.getText());
        double fSSP = Double.parseDouble(txtFirstPrice.getText());
        double sP = Double.parseDouble(txtSleepPrice.getText());
        double fSP = Double.parseDouble(txtFirstSleepPrice.getText());
        
        RailwayCompany railwayCompany = (RailwayCompany)origanization;
        List<request> requests = railwayCompany.getRequestDirectory().getRequestList();
        for (request request : requests) {
            if (request instanceof TrainLine) {
                TrainLine trainLine = (TrainLine)request;
                if (this.trainLine.getId() != trainLine.getId() && trainLine.getId() == Integer.parseInt(id)) {
                    JOptionPane.showMessageDialog(null, "Route number already exists!");
                    return;
                }
                if (trainLine.getStartDate() != null && 
                    trainLine.getCaptain() != null &&
                    this.trainLine.getId() != trainLine.getId() &&
                    sdf.format(sDate).substring(0, 5).equals(sdf.format(trainLine.getStartDate()).substring(0, 5))
                    && conductor.getData().getId() == trainLine.getCaptain().getId()) {
                    JOptionPane.showMessageDialog(null, "The same person can only arrange one shift a day!");
                    return;
                }
                
            }
        }
        if (deStation.equals(inStation) || laStation.equals(inStation) || deStation.equals(laStation)) {
            JOptionPane.showMessageDialog(null, "Train station repeat!");
            return;
        }
        
        trainLine.setRequestPersonId(employee.getId()+"");
        trainLine.setOrganizationId(origanization.getId());
        trainLine.setType(type);
        trainLine.setStatus(status);
        trainLine.setStartDate(sDate);
        trainLine.setId(Integer.parseInt(id));
        ArrayList<String> sL = new ArrayList<>();
        sL.add(deStation);
        sL.add(inStation);
        sL.add(laStation);
        trainLine.setTrainLine(sL, 0, conductor.getData(), train.getData(), rSS, rFSS, rS, rFS, sSP, fSSP, sP, fSP);
        DB4OUtil.getInstance().storeSystem(system);
        // Information Added Succesfully!
        JOptionPane.showMessageDialog(null, "Information Updated Succesfully!");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ShowRouteJPanel rwajp = new ShowRouteJPanel(userProcessContainer, employee, system, origanization);
        userProcessContainer.add("ShowRouteJPanel", rwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbIntermediateStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIntermediateStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIntermediateStationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<BoxHelper<Employee>> cmbConductor;
    private javax.swing.JComboBox<String> cmbDeStation;
    private javax.swing.JComboBox<String> cmbIntermediateStation;
    private javax.swing.JComboBox<String> cmbLandStation;
    private javax.swing.JComboBox<BoxHelper<Train>> cmbTrainId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIntermediateStation;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle13;
    private javax.swing.JLabel lblTitle14;
    private javax.swing.JLabel lblTitle15;
    private javax.swing.JLabel lblTitle16;
    private javax.swing.JLabel lblTitle17;
    private javax.swing.JLabel lblTitle18;
    private javax.swing.JLabel lblTitle19;
    private javax.swing.JLabel lblTitle20;
    private javax.swing.JLabel lblTitle21;
    private javax.swing.JLabel lblTitle22;
    private javax.swing.JLabel lblTitle23;
    private javax.swing.JLabel lblTitle24;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel txtBusi;
    private javax.swing.JTextField txtDeDate;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtFirstPrice;
    private javax.swing.JTextField txtFirstSleepNum;
    private javax.swing.JTextField txtFirstSleepPrice;
    private javax.swing.JTextField txtRouteNum;
    private javax.swing.JTextField txtRouteType;
    private javax.swing.JTextField txtSecondNum;
    private javax.swing.JTextField txtSecondPrice;
    private javax.swing.JTextField txtSleepPrice;
    private javax.swing.JTextField txtSleeperNum;
    private javax.swing.JTextField txtStatusField;
    // End of variables declaration//GEN-END:variables
}
