/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import api.TravelSystem;
import api.organization.Organization;
import api.userAccount.UserAccount;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 10857
 */
public class CustomerOrders extends javax.swing.JPanel {

    /**
     * Creates new form CustomerOrders
     */
    private TravelSystem system;
    private UserAccount account;
    private Organization organization;
    private double discount;
    public CustomerOrders(TravelSystem system, UserAccount account, Organization organization) {
        initComponents();
        this.system = system;
        this.account = account;
        this.organization = organization;
        
        if(this.account.getRole().getRole().equals("Customer")){
            BtnVIPF.setVisible(false);
            CbxOrderType.setVisible(false);
            lblOrderType.setVisible(false);
        }
        this.populate(0);
    }

    public void populate(int mode){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int rowNumber = model.getRowCount();
        for(int i = 0; i < rowNumber;i++){
            model.removeRow(0);
        }
        for(int i = 0; i < account.getRequestDirectory().getRequestList().size(); i++){
            
            if(mode == 0 && account.getRequestDirectory().getRequestList().get(i).getType().contains("Ticket")){
                Object[] row = new Object[4];
                row[0] = account.getRequestDirectory().getRequestList().get(i).getId();
                row[1] = account.getRequestDirectory().getRequestList().get(i).getOrganizationId();
                row[2] = account.getRequestDirectory().getRequestList().get(i).getType();
                SimpleDateFormat ft = new SimpleDateFormat ("MM-dd HH:mm");
                row[3] = ft.format(account.getRequestDirectory().getRequestList().get(i).getStartDate());
                model.addRow(row);
            }
            if(mode == 1 && (account.getRequestDirectory().getRequestList().get(i).getType().equals("VIP"))){
                Object[] row = new Object[4];
                row[0] = account.getRequestDirectory().getRequestList().get(i).getId();
                row[1] = account.getRequestDirectory().getRequestList().get(i).getOrganizationId();
                row[2] = account.getRequestDirectory().getRequestList().get(i).getType();
                SimpleDateFormat ft = new SimpleDateFormat ("MM-dd HH:mm");
                row[3] = ft.format(account.getRequestDirectory().getRequestList().get(i).getStartDate());
                model.addRow(row);                
            }
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblOrderType = new javax.swing.JLabel();
        CbxOrderType = new javax.swing.JComboBox<>();
        BtnCancel = new javax.swing.JButton();
        BtnDetail = new javax.swing.JButton();
        BtnVIPF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        jLabel1.setText("My Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 46, -1, -1));

        table.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderId", "OrganizationId", "Type", "StartDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 168, 922, 370));

        lblOrderType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        lblOrderType.setText("Order Type: ");
        add(lblOrderType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 112, -1, 30));

        CbxOrderType.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        CbxOrderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "VIP" }));
        CbxOrderType.setToolTipText("");
        CbxOrderType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxOrderTypeItemStateChanged(evt);
            }
        });
        add(CbxOrderType, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 109, -1, 30));

        BtnCancel.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        add(BtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 556, 110, 40));

        BtnDetail.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BtnDetail.setText("Detail");
        BtnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetailActionPerformed(evt);
            }
        });
        add(BtnDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 556, 110, 40));

        BtnVIPF.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BtnVIPF.setText("Request VIP Flight or Line");
        BtnVIPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVIPFActionPerformed(evt);
            }
        });
        add(BtnVIPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 46, 240, -1));

        jButton1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 556, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Customer/customer6_副本.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 0, 198, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CbxOrderTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxOrderTypeItemStateChanged
        // TODO add your handling code here:
        if(CbxOrderType.getSelectedItem().toString().equals("Normal")){
            this.populate(0);
        }
        else{
            this.populate(1);
        }
    }//GEN-LAST:event_CbxOrderTypeItemStateChanged

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this,"Please select a row");
        }
        else{
            for(int i = 0; i < account.getRequestDirectory().getRequestList().size(); i++){
                if(account.getRequestDirectory().getRequestList().get(i).getId() == Integer.valueOf(table.getValueAt(row, 0).toString()) && account.getRequestDirectory().getRequestList().get(i).getOrganizationId().equals(table.getValueAt(row, 1).toString())){
                    account.getRequestDirectory().getRequestList().get(i).setStatus("Canceled");
                }
            }
            if(CbxOrderType.getSelectedItem().toString().equals("Normal")){
                this.populate(0);
            }
            else{
                this.populate(1);
            }
        }
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetailActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        
        if(row == -1){
           JOptionPane.showMessageDialog(this,"Please select a row"); 
        }
        else{
            for(int i = 0; i < account.getRequestDirectory().getRequestList().size(); i++){
                if(account.getRequestDirectory().getRequestList().get(i).getId() == Integer.valueOf(table.getValueAt(row, 0).toString()) && account.getRequestDirectory().getRequestList().get(i).getOrganizationId().equals(table.getValueAt(row, 1).toString())){
                    OrderDetail or = new OrderDetail(this.account, account.getRequestDirectory().getRequestList().get(i) , this.system, this.organization);
                    or.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_BtnDetailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(CbxOrderType.getSelectedItem().toString().equals("Normal")){
            this.populate(0);
        }
        else{
            this.populate(1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnVIPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVIPFActionPerformed
        // TODO add your handling code here:
        OrderDetail or = new OrderDetail(this.account, null, this.system, this.organization);
        or.setVisible(true);
    }//GEN-LAST:event_BtnVIPFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnDetail;
    private javax.swing.JButton BtnVIPF;
    private javax.swing.JComboBox<String> CbxOrderType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
