/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import java.awt.CardLayout;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import business.DB4OUtil.UserDBUtil;
import business.dto.OrganizationDto;
import business.dto.PersonDto;
import business.dto.RoleDto;
import business.dto.UserDto;
import business.exception.CommonException;
import business.type.OrganizationType;
import business.type.RoleType;

/**
 *
 * @author Lynn Wei
 */
public class ManageRestaurantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployee
     */
    JPanel userProcessContainer;
    UserDto userDto;
    UserDto selectedUserDto;
    int rowIndex = -1;
    
    public ManageRestaurantJPanel(JPanel userProcessContainer, UserDto userDto) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userDto = userDto;
    }
    
    public void initCustomerTable(UserDto userDto) {
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
        Object[] row = new Object[5];
        row[0] = userDto.getPerson().getPersonName();
        row[1] = userDto.getUserName();
        row[2] = userDto.getRestaurantName();
        row[3] = userDto.getRole().getRoleName();
        row[4] = userDto.getId();
        model.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        lblUsersList = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblRestaurantManagerInfo = new javax.swing.JLabel();
        txtPerson = new javax.swing.JTextField();
        txtRole = new javax.swing.JTextField();
        txtRole.setText(RoleType.RestaurantAdmin.getValue());
        lblRole2 = new javax.swing.JLabel();
        lblOrganization2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblPassword2 = new javax.swing.JLabel();
        lblUserName2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPerson = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtOrganization = new javax.swing.JTextField();
        txtOrganization.setText(OrganizationType.Restaurant.getValue());
        btnUpdate = new javax.swing.JButton();
        lblRestaurantName = new javax.swing.JLabel();
        txtRestaurantName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();

        lblUsersList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsersList.setText(" Restaurant Managers List:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle1.setText("Manage Restaurant Managers");

        lblRestaurantManagerInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRestaurantManagerInfo.setText("Restaurant Manager Info:");

        txtPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonActionPerformed(evt);
            }
        });

        lblRole2.setText("Role:");

        lblOrganization2.setText("Organization:");

        lblPassword2.setText("Password:");

        lblUserName2.setText("User Name:");

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserName4ActionPerformed(evt);
            }
        });

        lblPerson.setText("Person:");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCreate.setText("Add");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblRestaurantName.setText("Restaurant Name:");

        List<UserDto> userList = 
            UserDBUtil.queryByOrg(OrganizationType.Restaurant.getValue());
        Object[][] dataList = new Object[userList.size()][5];
        for (int i = 0; i < dataList.length; i++) {
            dataList[i][0] = userList.get(i).getPerson().getPersonName();
            dataList[i][1] = userList.get(i).getUserName();
            dataList[i][2] = userList.get(i).getRestaurantName();
            dataList[i][3] = userList.get(i).getRole().getRoleName();
            dataList[i][4] = userList.get(i).getId();
        }
        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            dataList,
            new String [] {
                "Person", "User Name", "Restaurant", "Role", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomers);
        tblCustomers.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    return;
                }
                int i = tblCustomers.getSelectedRow();
                if (i < 0) {
                    return;
                }
                String id = (String)tblCustomers.getValueAt(i, 4);
                UserDto userDto = UserDBUtil.queryById(id);
                txtOrganization.setText(userDto.getOrganization().getOrgnaizationName());
                txtRole.setText(userDto.getRole().getRoleName());
                txtPerson.setText(userDto.getPerson().getPersonName());
                txtUserName.setText(userDto.getUserName());
                txtPassword.setText(userDto.getPassword());
                txtRestaurantName.setText(userDto.getRestaurantName());
                selectedUserDto = userDto;
                rowIndex = i;
            }
        });
        // ����������
        TableColumn tc = tblCustomers.getTableHeader().getColumnModel().getColumn(4);
        tc.setMaxWidth(0);
        tc.setWidth(0);
        tc.setMinWidth(0);
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblRestaurantName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblRole2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblOrganization2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblUserName2)
                                            .addComponent(lblPassword2)
                                            .addComponent(lblPerson))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblRestaurantManagerInfo)
                                        .addGap(135, 135, 135))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsersList)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(130, 130, 130)
                                .addComponent(lblTitle1)))
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsersList)
                    .addComponent(lblRestaurantManagerInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrganization2)
                            .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRole2)
                            .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRestaurantName)
                            .addComponent(txtRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerson))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName2)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword2)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SystemAdminWorkAreaJPanel sawajp = new SystemAdminWorkAreaJPanel(userProcessContainer, userDto);
        userProcessContainer.add("SystemAdminWorkAreaJPanel", sawajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUserName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserName4ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
        UserDto userDto = UserDBUtil.queryById(selectedUserDto.getId());
        UserDBUtil.remove(userDto);
        model.removeRow(rowIndex);
        txtUserName.setText("");
        txtPassword.setText("");
        txtPerson.setText("");
        txtRestaurantName.setText("");
        selectedUserDto = null;
        rowIndex = -1;
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String orgnaizationName = txtOrganization.getText();
        String roleName = txtRole.getText();
        String person = txtPerson.getText();
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        String restaurantName = txtRestaurantName.getText();
        if (person.isEmpty() || userName.isEmpty() || password.isEmpty()) {
            return;
        }
        UserDto userDto = new UserDto(userName, password, new RoleDto(roleName), 
            new OrganizationDto(orgnaizationName), new PersonDto(person), restaurantName);
        try {
            UserDBUtil.save(userDto);
        } catch (CommonException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        initCustomerTable(userDto);

        JOptionPane.showMessageDialog(null, "Restaurant added successfully.");
        txtUserName.setText("");
        txtPassword.setText("");
        txtPerson.setText("");
        txtRestaurantName.setText("");
        selectedUserDto = null;
        rowIndex = -1;
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // add your handling code here:
        String orgnaizationName = txtOrganization.getText();
        String roleName = txtRole.getText();
        String person = txtPerson.getText();
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        String restaurantName = txtRestaurantName.getText();
        if (person.isEmpty() || userName.isEmpty() || password.isEmpty() || rowIndex < 0 || null == selectedUserDto) {
            return;
        }
        selectedUserDto.setUserName(userName);
        selectedUserDto.setPassword(password);
        selectedUserDto.getPerson().setPersonName(person);
        selectedUserDto.getRole().setRoleName(roleName);
        selectedUserDto.getOrganization().setOrgnaizationName(orgnaizationName);
        selectedUserDto.setRestaurantName(restaurantName);
        try {
            UserDBUtil.update(selectedUserDto);
        } catch (CommonException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        tblCustomers.getModel().setValueAt(selectedUserDto.getPerson().getPersonName(), rowIndex, 0);
        tblCustomers.getModel().setValueAt(selectedUserDto.getUserName(), rowIndex, 1);
        tblCustomers.getModel().setValueAt(selectedUserDto.getRestaurantName(), rowIndex, 2);
        tblCustomers.getModel().setValueAt(selectedUserDto.getRole().getRoleName(), rowIndex, 3);
        JOptionPane.showMessageDialog(null, "Restaurant updated successfully.");
        txtUserName.setText("");
        txtPassword.setText("");
        txtPerson.setText("");
        selectedUserDto = null;
        rowIndex = -1;
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrganization2;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JLabel lblRestaurantManagerInfo;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblRole2;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JLabel lblUsersList;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtOrganization;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPerson;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
