/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Airport;

import api.organization.Airport;
import api.property.Gate;
import api.property.Road;
import api.request.Landing;
import ui.captain.*;
import ui.Airport.*;
import ui.AirlineCompany.*;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author wangqingtang
 */
public class LandingPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightInfoPanel
     */
    JPanel container;
    Airport airport;
    Landing landing;
    public LandingPanel(JPanel container, Airport airport, Landing landing) {
        initComponents();
        this.container = container;
        this.airport = airport;
        this.landing = landing;
        populateTable();
    }
    
    private void populateTable(){
        setCbxModel(cbxRoad, this.airport.getRoadList().toArray());
        setCbxModel(cbxGate, this.airport.getGateList().toArray());
    }

    public void setCbxModel(javax.swing.JComboBox<Object> cbx, Object[] data) {
        cbx.setModel(new javax.swing.DefaultComboBoxModel<>(data));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        cbxRoad = new javax.swing.JComboBox<>();
        cbxGate = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle1.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle1.setText("Road:");
        add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Airport/Backbutton_3.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 50, 60));

        jButton2.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 149, 42));

        lblTitle2.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle2.setText("Flight Request");
        add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 33, -1, -1));

        lblTitle3.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        lblTitle3.setText("Gate:");
        add(lblTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        cbxRoad.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(cbxRoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 180, -1));

        cbxGate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        add(cbxGate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Airport/airplane.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 710, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
	CardLayout layout = (CardLayout) container.getLayout();
	layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Road road = (Road) cbxRoad.getSelectedItem();
        Gate gate =  (Gate) cbxGate.getSelectedItem();
        this.airport.getRoadList().remove(road);
        this.airport.getGateList().remove(gate);
        landing.setRoad(road);
        landing.setGate(gate);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cbxGate;
    private javax.swing.JComboBox<Object> cbxRoad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    // End of variables declaration//GEN-END:variables
}
